### ISSUE TITLE
Getting NGROK's default page while accessing App Proxy URL

### ISSUE THREAD

**Issue by rehancse** [kinngh/shopify-node-express-mongodb-app#102]
Hi @kinngh, I am using your boilerplate for Shopify App and learing a lot. I have also installed Shopify theme extension and want to use App Proxy. I followed documentation yet I got stuck in App proxy. I am getting NGROK's default page while visiting to Url. Even after clicking VISIT SITE it is not working. I am on the same page.
App proxy Url: https://sandbox-os-2-0.myshopify.com/apps/express-proxy/json

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/64255488/10518df7-34b0-4892-ae54-efa2ecd95f94)

**Comment by kinngh** [comment]
You need to send bypass headers if you're stuck on this page. This is a known ngrok issue. 

https://stackoverflow.com/questions/73017353/how-to-bypass-ngrok-browser-warning
