### ISSUE TITLE
getting the errror Cannot GET /  while installing the app

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#106]
hi @kinngh  

I followed the all the setup as per the setup guide.

issue reproduce  steps 
1. download the code 
2. npm i --force
3. update the .env all the value (correct)
4. npm run dev
5.  app install using -  https://ngrokurl.io/auth?shop=mystorename.myshopify.com
6. get the correct auth screen
7. app installing working. 
8. redirect time getting the error  Cannot GET / 
![Screenshot from 2023-10-10 19-12-18](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/114073623/9152cbcf-3a64-45a6-bc2f-b43801bc7f33)

more info - i can see the MongoDB collection is created.

**Comment by kinngh** [comment]
1. Cannot replicate
2. What port is your `ngrok` running on? Did you `npm run ngrok` or did you run ngrok directly by using `ngrok http 3000`?

https://github.com/kinngh/shopify-node-express-mongodb-app/assets/773555/8925aa6e-335b-4671-af22-29f2d8405ec5

**Comment by adventuretocode** [comment]
yes I am  runing the ngrok directly by using ngrok http 3000.

**Comment by adventuretocode** [comment]
@kinngh  One more issue why the user experience when the app starting first time show the app UI component then it was redirect and again the render the the app UI. this was  UX issue. this also in your video screen. if you can make it batter that was highly appreciated.

**Comment by kinngh** [comment]
> yes I am  runing the ngrok directly by using ngrok http 3000. 
> 
> 
> 
> for the 
> 
> `$  npm run ngrok:auth`
> 
> 
> 
> ![Screenshot from 2023-10-12 11-51-07](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/114073623/f531cbe4-3eca-4a36-98a2-8cd59e49bed9)
> 
> 

Please tell me you're joking. You're supposed to add your ngrok auth tokens there and then run npm run ngrok because we aren't only just using port 3000

**Comment by kinngh** [comment]
> @kinngh  One more issue why the user experience when the app starting first time show the app UI component then it was redirect and again the render the the app UI. this was  UX issue. this also in your video screen. if you can make it batter that was highly appreciated.  

That's AppBridge redirection. Nothing that can be done there.
