### ISSUE TITLE
Merchant Install Link Not Working for Custom App

### ISSUE THREAD

**Issue by egillanton** [kinngh/shopify-node-express-mongodb-app#109]
## Bug Description

The installation link provided for merchants to install the custom Shopify app is not working as intended. When merchants attempt to use the link to install the app directly, it fails to redirect to the _/auth_ route, which is necessary for initiating the Shopify OAuth process. Instead, merchants have to manually enter the URL _[SHOPIFY_APP_URL]/auth?shop=[STOREID].myshopify.com_.

## How to Reproduce

1. Setup an instance of this template (version 0.0.8).
2. In the Shopify Partner Dashboard, select the distribution method of the app as a custom app.
3. Generate a merchant install link for any store.
4. Attempt to open the generated URL.

## Expected behavior

Upon clicking the merchant link, if the user is not logged into their Shopify admin dashboard, the link should trigger a login prompt for the merchant and, post-login, redirect the user to the _/auth_ route to begin the Shopify OAuth process.

## Actual behavior

The merchant link does not redirect to the _/auth_ route, thus disrupting the installation process.

**Comment by kinngh** [comment]
Is it a prod deployment or are you trying to install in dev mode?

**Comment by egillanton** [comment]
@kinngh I have tried both prod and dev, and the same behavior

**Comment by kinngh** [comment]
Just tried this out in prod mode, cannot replicate. Can you list out, in exact detail, what your steps are? 

Besides, what's the problem with the URL format? I mean, if it works, it works, despite what it looks like because your merchant is more concerned about installing the app instead of what the URL format is
