### ISSUE TITLE
Turning the App into a Theme App Extension

### ISSUE THREAD

**Issue by Zafeldaf** [kinngh/shopify-node-express-mongodb-app#114]
Hi kinngh,

Sorry for disturbing you, but I have a question. This isn't a life-threatening error I am facing, just a simple question. Can I make a theme-app-extension using this template? 

So if I want to make or have made an app that interacts with the online store, can I turn it into a theme app extension? The CLI allows to create one but it needs to be one of Shopify's templates. If I wanted to turn it into a theme app extension how would I do that? Can I just run the CLI command? 

Thanks for helping me, take your time.

**Comment by kinngh** [comment]
1. Stop apologizing.
2. Yes! Take a look at this repo that _is only suppposed to be used as a reference_ on how apps with extensions and other things should look like: https://github.com/kinngh/shopify-app-js . In short, your app and extensions need to be in separate folders and you can copy the package.json from this repo's extension folder and you'll be good to go!

**Comment by Zafeldaf** [comment]
Thank you very much, mate. Helped me a lot. And I'll stop apologizing now.
