### ISSUE TITLE
GDPR not working

### ISSUE THREAD

**Issue by i-moreno** [kinngh/shopify-node-express-mongodb-app#12]
I think that GDPR for this is not working.

`TypeError: Cannot read properties of undefined (reading 'webhookSubscriptions')`

Looks like gdpr must be registered in a different way

https://github.com/Shopify/shopify-api-node/issues/290#issuecomment-1034844736

**Comment by kinngh** [comment]
Hey! Ye that is pending testing. I have an implementation already setup and waiting on few other devs to verify before I push it^

I'll attach the commit before I close the issue, but it's being actively worked on!

**Comment by kinngh** [comment]
I have a provisional commit so you can test it out too [3985](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/22650950280edb513e41617964234643a5593985)^

**Comment by i-moreno** [comment]
Awesome work man, that works for me.

**Comment by kinngh** [comment]
@i-moreno ^
