### ISSUE TITLE
404 - There's no page at this address

### ISSUE THREAD

**Issue by Amtron** [kinngh/shopify-node-express-mongodb-app#120]
Hi @kinngh,

I'm currently in the process updating my app (originally installed your boilerplate ~ July 2022) to your most recent release. 
I've updated all of the packages in package.json, gone over your most recent release and updated necessary files accordingly, but I may have missed something because I'm getting "404 There's no page at this address" in dev mode:

![Screen Shot 2024-03-05 at 7 12 46 am](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/0b4cbb48-d607-4ebd-b6c6-3e2a3fc4974e)

My process for starting dev is as follows:
1) start ngrok `ngrok http 5173`
2) get ngrok address and update SHOPIFY_APP_URL and VITE_SHOPIFY_API_KEY in .env
3) npm run dev
4) npm run update:url
5) use installation URL to install app into my dev store on shopify

Once 5)  is executed I hit the 404

Here is a screen grab of my ngok terminal:
<img width="1286" alt="Screen Shot 2024-03-05 at 7 18 04 am" src="https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/03ac433e-8e71-45d4-8757-0b53e225fbd9">

This is a screen grab of my dev terminal:
<img width="1249" alt="Screen Shot 2024-03-05 at 7 19 30 am" src="https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/cf51acac-7690-4a57-a812-fb255387209e">

@kinngh , As usual, thanks for this fantastic boilerplate; you're a legend!

**Comment by kinngh** [comment]
Thank you so much for the kind words! This is how I'd debug this:
1. Clear the `stores` and `session` tables
2. In dev mode, you need to use the install link `https://appurl/api/auth?shop=store.myshopify.com` instead of using the Partner dashboard because that's broken (fix is coming soon ™ )
3. If you're still stuck, happy to hop on a call (ping me on [Twitter](https://twitter.com/kinngh))

**Comment by Amtron** [comment]
Tried 1 and 2, unfortunately no luck. DM'd you.

**Comment by kinngh** [comment]
Config issue - problems when merging into a newer version
