### ISSUE TITLE
How to setup the production install route?

### ISSUE THREAD

**Issue by afraz-khan** [kinngh/shopify-node-express-mongodb-app#123]
I have created a separate app installation path at `/api/auth` as you did but this doesn't work in production where merchants will install the app from the App Store using the big install button on the app page.

I have read that ([here](https://shopify.dev/docs/apps/auth/get-access-tokens/authorization-code-grant/getting-started#step-1-verify-the-installation-request:~:text=When%20a%20user%20installs%20your%20app%20through%20the%20Shopify%20App%20Store%20or%20using%20an%20installation%20link%2C%20your%20app%20receives%20a%20GET%20request%20to%20the%20App%20URL%20path%20that%20you%20specify%20in%20the%20Partner%20Dashboard.%20The%20request%20includes%20the%20shop%2C%20timestamp%2C%20and%20hmac%20query%20parameters.)), Shopify sends the app installation request at `https://{APP_URL}/?shop=xxx.myshopify.com&&hmac=329en239e82e923e23e23e23&&timestamp=32847239`.

How do we handle that in the code?

Or do you know about any seamless app installation methods in production? Pl share

**Comment by kinngh** [comment]
1. I don't understand what you're doing with `I have created a separate app installation path at...`. The repo comes with everything in built so you don't have to create anything manually to interact with Shopify
2. You do not need to handle any of that in code. That is something that's already handled by default

**Comment by afraz-khan** [comment]
@kinngh I have done nothing new, I'm simply inquiring about the functionality of the installation process in a production environment if I use this codebase.

According to documentation [here](https://shopify.dev/docs/apps/auth/get-access-tokens/authorization-code-grant/getting-started#step-1-verify-the-installation-request:~:text=When%20a%20user%20installs%20your%20app%20through%20the%20Shopify%20App%20Store%20or%20using%20an%20installation%20link%2C%20your%20app%20receives%20a%20GET%20request%20to%20the%20App%20URL%20path%20that%20you%20specify%20in%20the%20Partner%20Dashboard.%20The%20request%20includes%20the%20shop%2C%20timestamp%2C%20and%20hmac%20query%20parameters.), Shopify hits the app URL to send the installation request to the app. However, I'm currently uncertain about how we're managing this process within our Express codebase and how we're directing users to the authorization screen in response to the initial installation request in a production environment.

**Comment by kinngh** [comment]
When the install button is hit, the middle wares check if the shop is active, if it's not, redirect to the /api/auth route. If you spent a minute looking at the server/index.js file you'd understand this. 

It's not that complicated. There's quite a few devs who use this boilerplate in production, including me.

**Comment by afraz-khan** [comment]
I have been searching for the `/exitframe` calling from the backend and have just located it within the implementation of `/api/auth`. sorry for my ignorance, I appreciate your clarification. I will now close this issue.
