### ISSUE TITLE
Theme App Extension 

### ISSUE THREAD

**Issue by zohaibarsalan** [kinngh/shopify-node-express-mongodb-app#126]
Hello, once again Kinngh.

I questioned you previously about adding theme-app-extensions to my application and I did do that. I put the generate extension script in my package.json and made an extension through the Shopify CLI. The CLI generated the extensions folder in which I have the normal files and folder. I even see the extension for my app in the extensions tab in the Partners dashboard. However, I do not know how to view or run the extension. I don't see the extension in the online store customizer.

**package.json**
 ```
"scripts": {
    "dev": "concurrently \"npm run dev:*\"",
    "dev:server": "NODE_ENV=dev nodemon server/index.js --ignore client/ --ignore dist/",
    "dev:client": "vite --config=./client/vite.config.cjs",
    "build": "vite build --config=./client/vite.config.cjs",
    "start": "NODE_ENV=prod node server/index.js",
    "-----> utils <-----": "",
    "update": "ncu -u",
    "update:url": "node _developer/updateDashboard.js",
    "pretty": "prettier --write .",
    "-----> tunneling <-----": "",
    "-----> ngrok <-----": "",
    "ngrok:auth": "ngrok authtoken <your-auth-token>",
    "ngrok": "ngrok http 5173",
    "ngrok:prod": "ngrok http 8081",
    "-----> cloudflare <-----": "",
    "cloudflare": "cloudflared tunnel --url localhost:5173",
    "cloudflare:prod": "cloudflared tunnel --url localhost:8081",
    "-----> Shopify <-----": "",
    "g:install": "npm i -g @shopify/app@latest @shopify/cli@latest",
    "shopify": "shopify",
    "info": "shopify app info",
    "generate": "shopify app generate extension",
    "deploy": "shopify app deploy",
    "-----> Reserved Scripts <-----": "",
    "preserve": "npm run build"
  },
```

**shopify.extension.toml**
```
name = "bannerito"
type = "theme"
```

**Partners Dashboard**
![Partners Dashboard](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/59132383/47f1a353-3ae0-4212-9655-83f864b1c08d)

I would greatly appreciate it if you helped me figure out how to run the extension in conjunction with my normal application.

Cheers,
Zohaib :)

**Comment by kinngh** [comment]
You run your extension separately from your main app. Here's an example of how to structure your app and have things work: https://github.com/kinngh/shopify-app-js

Also, this should've been a discussion, not an issue. Please be mindful from the next time and post in the right space.

**Comment by zohaibarsalan** [comment]
I'm sorry I didn't put this in the correct space. 

I have one last question, I add this to my main package.json

```
 "dev:extension": "shopify app dev",
```

And then run this in the main folder with conjunction to the actual application?

**Comment by kinngh** [comment]
1. Make sure that your `extension` folder isn't inside the `app` folder
2. Your extension and app need to be in separate folders
3. In your app folder, run `npm run dev`
4. In your extension folder, run `shopify app dev`

**Comment by zohaibarsalan** [comment]
Is this the correct structure of the extension folder?
![Folder Structure](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/59132383/3fbb1a7a-de5f-4802-96ba-4302b91e1465)

**Comment by zohaibarsalan** [comment]
Actually, nevermind it works. Thank you, Kinng for all the help. Once again I am sorry for not uploading this in the correct space. And thank you for taking out time to help me.

**Comment by kinngh** [comment]
Nah don't worry about it! Also again, this is exactly what I've been saying - your app and extensions folder need to be at the same level, and the extension folder shouldn't be inside the app folder (the app folder should include `server/`, `utils/`, `_developer/`, `client/`, etc)

**Comment by zohaibarsalan** [comment]
Yep I got it thanks to you. 

Do you have any idea how I can take data from my app and pass it to embedded theme blocks? Like the user in my app inputs his slogan and that slogan is then taken to a block and I can use that data as the slogan

**Comment by kinngh** [comment]
Make an app proxy and use a `fetch()` to get data from your app

**Comment by zohaibarsalan** [comment]
The proxy isn't working. I am using the already-written proxy controller.

Partners Dashboard:
![Prixy Settings - Partner Dashboard](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/59132383/347eb9ec-ec9d-48e1-81cd-0876bb967443)

app_proxy/index.js
```js
import { Router } from 'express';
import clientProvider from '../../../utils/clientProvider.js';
const proxyRouter = Router();

proxyRouter.get('/json', async (req, res) => {
  const { client } = await clientProvider.offline.graphqlClient({
    shop: res.locals.user_shop,
  });
  return res.status(200).send({ content: 'Proxy Be Working' });
});
export default proxyRouter;
```

test.liquid
```liquid
<script>
  fetch("/apps/test-app/json")
     .then((res) => console.log("Data from proxy ", res))
     .catch((error) => console.log("Error from proxy", error))
</script>
```

Response in console:
![Prpxy Response in Console](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/59132383/51cbf8d8-eda7-4540-9aec-5cb3bbb73fd8)

**Comment by zohaibarsalan** [comment]
Ok Kiingh I got it. It was because of ngrok. I went put this 

```
https://my-store.myshopify.com/apps/test-app/json
```

in the browser and used requestly to make sure the ngrok request header browsing warning was set to true and then I got the json with the response that the proxy works. 

In the end it was because of ngrok. 

I think I am going to switch to cloudflare, do you have any tips or tutorial on how to switch?

**Comment by kinngh** [comment]
Just swap out `ngrok` with `cloudflared` in `package.json` after installing the right packages for your system and you'll be good to go!
