### ISSUE TITLE
Fix Needed: 'Refused to Connect' Error and Add Session Tokens to Your Shopify App

### ISSUE THREAD

**Issue by kmajay978** [kinngh/shopify-node-express-mongodb-app#132]
Hello @kinngh,

Thanks for creating this package. I have been using it for all my Shopify app projects. Recently, I encountered an error during the app approval process. They rejected my app due to the following issue: **"Your embedded app must use session tokens and not rely on 3rd party cookies to function properly"** in Chrome Incognito mode. The app works fine in other browsers, but their criteria specifically require it to function in Chrome's private window.

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/75435942/b3894091-477b-4acb-9d6c-5ff4cab68663)

To address this issue, I tried implementing the patch you shared on GitHub, but it did not resolve the problem. The app works fine in development but fails multiple times on the production server.

After investigating, I realized that the base boilerplate primarily functions with browser cookies, local storage, or session storage (browser-based). However, Shopify requires the app to load and work with database storage, not browser storage, I believe.

I never faced this issue with this package before. I thought it might be a reviewer issue, so I contacted their app support for a resolution. They informed me that this is part of their new guidelines: **"The other issue that has been flagged is that an embedded app must use session tokens."**

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/75435942/b97915a9-87bb-4e4e-827d-33a5249cad8b)

Here is the complete email I received from them:

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/75435942/8bc1d396-3adf-4e63-96af-f9fc50388701)

I hope we can find a resolution to bypass this core requirement. Kindly check and help me out.

Thanks & Regards
Ajay kumar

**Comment by kinngh** [comment]
Marking this as investigating. Let me try and get a resolution on this in the next 24 hours^

**Comment by kinngh** [comment]
Also, going through this again, I don't explicitly use any cookies / local store anywhere in the boilerplate and it mostly comes from Shopify's package, given the script literally edits cookies. Moving on to session tokens, that's just the reviewer being, for the lack of a better term, dumb. [SessionHandler](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/main/utils/sessionHandler.js), [VerifyRequest](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/main/server/middleware/verifyRequest.js) and more explicitly work with tokens. It's just copy / paste text for the issues they find and mislead devs into thinking what they're doing is wrong.

**Comment by kmajay978** [comment]
Thanks for your quick reply. I checked the server logs, but I haven't found anything. It seems this package isn't working with any custom storage or database techniques to handle this part. Also, I realized that if someone uses this package, they will face this issue during the review process.

In the past, it wasn't necessary, but now they are more serious about this part.

I think we need to identify and handle this in the package for future purposes.

**Comment by kinngh** [comment]
Use of cookies has been rejected for quite some time, and it's not about them being strict, it's about the base Shopify packages changing something that's affecting the repository. Managed Install fixes a lot of these issues so migrating there would almost instantly deal with these problem sets, which I'm finishing up atm

**Comment by kinngh** [comment]
Also, about error logs, it's not about what you can see, it's about sending me the error logs so I know what's happening. This is why I've been increasingly rude towards devs who do not have the baseline IQ to post server and browser logs.

**Comment by kmajay978** [comment]
I understand your concern. It requires server logs to investigate this issue. Based on my research, there are no server logs available on my Nginx server. Additionally, I am using PM2, and I still haven't found any issues or errors in my server log.  Otherwise, i am happy to share the server logs if generated. 

**Here is the browser log** 
Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

Refused to frame 'https://maketrip.myshopify.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

**I tried both, but there is nothing.**
1. error_log /var/log/nginx/error.log;
2. pm2 logs

**Comment by kinngh** [comment]
1. Even if you can't see the God damn errors, I want the logs.
2. That's a CSP issue, ensure your `server/index.js` actually has `app.use(csp)` before you serve your routes.

**Comment by kinngh** [comment]
Fixed in [c747c](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/c0b2d63eedc4eee156d29572d57bf6e0ba2c747c)

**Comment by kmajay978** [comment]
Thanks @kinngh, it's working perfectly. You're a lifesaver!
