### ISSUE TITLE
id_token not in request query in production

### ISSUE THREAD

**Issue by Amtron** [kinngh/shopify-node-express-mongodb-app#137]
Hi @kinngh,

I've recently migrated/updated my app to support "Managed installation". Everything works beautifully in dev, however I'm running into a client side installation loop when I try to install the app in production from the "install" button @ "https://apps.shopify.com/app_name".

Here's the install url from Shopify I"nstall" button, with the app name, handle  and hmac changed by me:
https://admin.shopify.com/store/[app_name]/apps/[app_handle]/?hmac=saduihsaduisahdsad8sad3&timestamp=1719522869

Here's the install url redirect for dev after using the "Quick auth URL":
https://admin.shopify.com/store/[app_name]/oauth/request_grant?access_change_uuid=dsdsdssdsdsdsdsdsdsdsdsd&client_id=sdsdsdsdsdsdsds

Dev installation works every time.

I've added a console.log to the "isInitialLoad" function and can report that the req.query returns the following params: hmac, host, shop, timestamp. id_token seems to be missing.

My .env variables have all been updated to match your ".env.example", the configuration on the app profile in the partners dashboard has been updated, all package versions in package.json have been updated and I've made sure that on deployment 
"node_packages" is deleted and all packages are reinstalled.

The app is deployed on Heroku and I have a feeling that this issue might be caused my caching or something ,but I really can't be sure. Do I need to run `npm run update:config` in production to generate a new toml file?

As always thanks for your time and this awesome boilerplate!

**Comment by kinngh** [comment]
Hey hey! I'm at Editions.dev right now and back on 1st July, I'll get back to you on this by 2nd. I do have some reports on this and looking into it whenever I get time in between events, but let me push one up as soon as I can. 

Leaving the issue open^

**Comment by kinngh** [comment]
Hey @Amtron , possible to get a video showing the console log and the URLs / direct dump after redacting PII? I'm looking into this and #135 and I believe they both can be related, but I need some more info to debug first

**Comment by kinngh** [comment]
@Amtron following up on this^

**Comment by Amtron** [comment]
Yo @kinngh,

Sorry for the late reply, I missed the notification.

I couldn't put together a video but here are some screen shots of the UX in order.

1) app store:
![app-store](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/c4613bc5-9694-43ac-864c-15fa52dec746)

2) after click install:
![after-click-install](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/94bcf883-0c82-4e49-a0ef-9babe27c2cda)

first url - https://[myapp-server].herokuapp.com/?hmac=[hmac hidden].&shop=[my shop].myshopify.com&timestamp=1720218795

redirects to - https://admin.shopify.com/store/[my shop]/apps/[my production app handle]/?hmac=[my hmac]&timestamp=1720218795

from here I can click the "Install" button but it loops back to the same install screen.

Screen shot of the server log after clicking install:
![server-logs-after-click-install](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/5695805/400c5ef5-ba29-4530-b30b-413a19a5078b)

starting at "2024-07-05T22:38:03.090481+00:00 app[web.1]" i console.log the following in order:

- shop - (looks fine)
- idToken - undefined
- req.query - {hmac, host, shop, timestamp}

Please let me know if I've missed anything or if you need something else.

**Comment by kinngh** [comment]
Just to confirm, you've pushed using npm run update:config script, right?

**Comment by Amtron** [comment]
I just modified my package.json script "heroku-postbuild". Previous it was "vite build --config=./client/vite.config.js" (which worked for older versions), now it's "npm run build && npm run update:config".

Now I get "sh: 1: shopify: not found" when trying to build on production.

Would you suggest that generate the toml on my local machine with all the production env values and then push that to my production server?

**Comment by kinngh** [comment]
Ok so `npm run update:config` is supposed to be run locally, and then you push it up. the `post build` script shouldn't be this. Let me double check the entire thing and post a better doc + everything else around it because IMO it's causing more confusion than I can tolerate

**Comment by Amtron** [comment]
> Ok so npm run update:config is supposed to be run locally

Makes sense.

This would mean that I'd need to keep a different .env for dev and production on my local and would need to switch between them before I run `npm run update:config`... Is this correct?

**Comment by kinngh** [comment]
@Amtron correct that's how I do it - though your config should mostly become stable after a certain point. If you're not pushing changes to your scopes or baselines in your `env`, you're not going to be using the command a lot in prod. In dev? Yes, a lot changes very often but that should stabilize after a certain point too (except for the tunneling URLs)

**Comment by Amtron** [comment]
This might seem like a silly question, but do I need to push the shopify.app.toml file to my production server or when I run `npm run update:config` does that automatically update the app credentials with Shopify?

**Comment by kinngh** [comment]
@Amtron  So the toml is only for pushing config up to Shopify and you don't need it to run your servers. I see now - I need to clear a lot of stuff up to make it make sense around with toml and other stuff

**Comment by Amtron** [comment]
@kinngh Okay I've got now. I've pushed the toml to Shopify and now I receive the token_id in the req.query.

Now I'm facing another issue, it could be related to #135 . When I get to 
```
      const webhookRegistrar = await shopify.webhooks.register({
        session: offlineSession,
      });
```

in isInitialLoad.js I'm getting this error:
```

 ---> An error occured in isInitialLoad HttpResponseError: Received an error response (406 Not Acceptable) from Shopify:
{
  "networkStatusCode": 406,
  "message": "GraphQL Client: Not Acceptable",
  "response": {
    "size": 0,
    "timeout": 0
  }
}
If you report this error, please include this id: 85542ee5-0397-4cb8-a54c-90ec0240445c-1720425025
  at throwFailedRequest (file:///app/node_modules/@shopify/shopify-api/dist/esm/lib/clients/common.mjs:106:19)
  at NewGraphqlClient.request (file:///app/node_modules/@shopify/shopify-api/dist/esm/lib/clients/admin/graphql/client.mjs:70:13)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async getExistingHandlers (file:///app/node_modules/@shopify/shopify-api/dist/esm/lib/webhooks/register.mjs:66:26)
  at async Object.register (file:///app/node_modules/@shopify/shopify-api/dist/esm/lib/webhooks/register.mjs:21:34)
  at async isInitialLoad (file:///app/server/middleware/isInitialLoad.js:31:32) {
response: {
  code: 406,
  statusText: 'Not Acceptable',
  body: { errors: [Object] },
  headers: { ....



```

**Comment by kinngh** [comment]
That issue is because you have "" in your environment variables in Heroku.

**Comment by Amtron** [comment]
@kinngh you are correct!

Thanks for your help and guidance!
