### ISSUE TITLE
Theme App Extension

### ISSUE THREAD

**Issue by bexelstudio** [kinngh/shopify-node-express-mongodb-app#14]
How can i add theme app extension ? since not using shopify cli here.

**Comment by kinngh** [comment]
You'll have to use the CLI for that. `shopify extension create` / `shopify extension connect` and then `shopify extension push` to push it to Shopify^

**Comment by kinngh** [comment]
Update: There's a new [commit](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/31fbb90b8e041532d64814da8495b87f026c3f06) that includes CLI 3.x along with 2 new scripts to create and deploy extensions.

`s:e:create`: Create new extension.
`s:e:deploy`: Deploy extension(s) to Shopify.

**Comment by nzmitch** [comment]
How do we create authenticated api calls from our theme app extensions?  I'm currently dealing with ... has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
