### ISSUE TITLE
404 in admin/app after install

### ISSUE THREAD

**Issue by Amtron** [kinngh/shopify-node-express-mongodb-app#15]
I'm having trouble getting the app to run in the admin dashboard. After I click install to my shop from the partner dashboard, it redirects me to "https://myngroksercer.io/?hmac=<hmacString>&shop=<myshop>.myshopify.com&timestamp=1659089273". The full screen loads at this address before it redirects me to "https://<myshop>.myshopify.com/admin/apps/<SHOPIFY_API_KEY>/?hmac=<hmacString>&shop=<myshop>.myshopify.com&timestamp=1659089273", and from here I get a "There’s no page at this address".

Has anyone had this issue?

**Comment by kinngh** [comment]
If you're using it in prod mode, you need to run `npm run build` before running `npm run start`. If you're in dev mode, macOS and Linux will work just fine when you use `npm run dev` but on Windows you might have to run `npm run build` `npm run dev` so it works as expected.

**Comment by Amtron** [comment]
I'm using macOS (ARM64), trying to use `npm run dev`. I've tried to `npm run build` before running `npm run dev` and I have also tried with`npm run start`. Still no luck.

**Comment by kinngh** [comment]
You recon we could hop on a call and see what's happening? It's a 100% user error and I'd like to update the docs if we figure out what's going wrong^

**Comment by kinngh** [comment]
Drop me a DM on [twitter](https://twitter.com/kinngh) please

**Comment by Amtron** [comment]
@kinngh Thanks for your help. 👍

**Comment by kinngh** [comment]
Always!

**Comment by rakibulmuhajir** [comment]
same issue. it displays the page for a moment before reloading to 404
