### ISSUE TITLE
Polaris 9.22 doesn't seem to support React 18

### ISSUE THREAD

**Issue by patrickbolle** [kinngh/shopify-node-express-mongodb-app#16]
I get this error when trying to install a package (after following SETUP.md and everything working fine originally):
`npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.14.0 || ^17.0.0" from @shopify/polaris@9.22.0
npm ERR!   node_modules/@shopify/polaris
npm ERR!     @shopify/polaris@"^9.22.0" from the root project`

Any ideas here? Not sure why it allowed me to do everything during initial setup but is now complaining.

It seems to be causing issues with any npm installation moving forward (but the app itself doesn't break, just npm complains)

Really great repo otherwise, thanks so much!

**Comment by kinngh** [comment]
Any package you install needs to be `npm i package_name --force` (or `npm i --force` for initial install) or it's going to cry about support. There are no known breaks at the moment, so you can be worry free about this! In the event something breaks, please open an issue and I'll be sure to look into it!
