### ISSUE TITLE
how to create the script tag

### ISSUE THREAD

**Issue by sanjay-ios-io** [kinngh/shopify-node-express-mongodb-app#20]
@kinngh  to create script tag getting error 503 

https://community.shopify.com/c/shopify-apis-and-sdks/how-to-create-script-tag-use-of-graphql/td-p/1702074
here is the code not getting response  from the graphql here is the code 
 
**https://github.com/sanjay-ios-io/shopify-apps-snnipest/blob/main/CreateScripttag.jsx
**
any steps guide to achieve the  Shopify graphql api.

**Comment by kinngh** [comment]
1. Issues are meant to be for issues with the repository ONLY.
2. This is not the right place to ask for issues with the Shopify API. Please use Shopify's Discord or Community forums.
