### ISSUE TITLE
Getting blank screen after clicking install

### ISSUE THREAD

**Issue by mahamudml** [kinngh/shopify-node-express-mongodb-app#21]
I have server side subscription on home page once homepage is loaded. 
In production I'm getting blank screen after clicking on install and following error message, it is still on SHOPIFY_APP_URL domain.

**Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.**

The app is installed, after going through admin>apps>My App it works fine

**Comment by kinngh** [comment]
I'm down with a viral fever so gonna be a little while before I can debug this, but can you please attach screenshots / screen records / snippets so I can take a look?

**Comment by mahamudml** [comment]
![image](https://user-images.githubusercontent.com/80940388/185649491-f7e47d6a-3ccb-4786-a8fa-6f997a7b2bf4.png)

**Comment by mahamudml** [comment]
After googling the issue I think it is because .js is missing while import

**Comment by mahamudml** [comment]
I tried in new ingonito tab and it is working now :|
