### ISSUE TITLE
Deprecated API calls made by app

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#25]
@kinngh  Please look into

![image](https://user-images.githubusercontent.com/114073623/193553086-436daa7c-d177-4430-ad07-b3649f3db15d.png)

**Comment by kinngh** [comment]
This has nothing to do with the boilerplate. Starting `2022-10`, you need to apply to access customer / sensitive data which can be done when you submit the app for review. Once you get those done, you won't have any errors.

Also, the `API CHANGE` section clearly states that you need to go through a review process to access customer protected data.

**Comment by adventuretocode** [comment]
Thanks lot @kinngh
