### ISSUE TITLE
authenticated Shopify Api request from theme-app-extension

### ISSUE THREAD

**Issue by nzmitch** [kinngh/shopify-node-express-mongodb-app#26]
My app creates Discounts for users after they verify ownership of a specific NFT. I'm using the Proxy route correctly and am able to retrieve necessary data from MongoDB to verify ownership but my /create-discount-code-auth Route throws an error.

I guess I need a hand understanding how to make authenticated Shopify API calls from Shopify's theme-app-extension. 

App proxy route
```
proxyRouter.get("/create-discount-code-auth", verifyRequest(proxyRouter), async (req, res) => {
  const session = await Shopify.Utils.loadCurrentSession(req, res, true);
  const { PriceRule } = await import(
    `@shopify/shopify-api/dist/rest-resources/${Shopify.Context.API_VERSION}/index.js`
  );

  const { DiscountCode } = await import(
    `@shopify/shopify-api/dist/rest-resources/${Shopify.Context.API_VERSION}/index.js`
  );

  const discount_code = Math.random().toString(36).slice(2, 24).toUpperCase();
  const rule_id = req.query.rule_id;
  const validity = req.query.validity;

  const start = new Date();
  const end = moment(start).add(Number(validity), "minutes").format();

  const price_rule = new PriceRule({ session });
  price_rule.id = rule_id;
  price_rule.starts_at = start;
  price_rule.ends_at = end;
  await price_rule.save({});

  const discount = new DiscountCode({ session });
  discount.price_rule_id = rule_id;
  discount.code = discount_code;

  try {
    await discount.save({});
    req.body = { message: `Discount code created [  ${discount_code}  ]` };
    res.status(200).json(req.body);
  } catch (error) {
    req.body = {
      message: `Discount code creation failed with error ${error.message}`,
    };
  }
});
```

Call from theme-app-extension
```
const createDiscountCode = async (rule_id, selected_discount_validity) => {
    const response = await Axios.get(`/apps/discount-express-proxy/create-discount-code-auth? 
    validity=${selected_discount_validity}&rule_id=${rule_id}`).then((response) => response.data);
    alert(response.message);
};

createDiscountCode(setSelectedRule, "15");
```

This Route works from inside my app but I am looking to trigger it on the storefront.

https://user-images.githubusercontent.com/33976247/194199386-be5922e0-29e5-4ec0-a939-29c245195842.mp4

![Screenshot 2022-10-06 151916](https://user-images.githubusercontent.com/33976247/194199662-d1abb9ed-8f61-44b8-b437-8bf3f770421d.jpg)

I'm posting here as I'm using your boilerplate and am hoping I've just missed a step.

Thanks.

**Comment by nzmitch** [comment]
Update: I was able to create a discount from the storefront using a different method but I had to hard code the shopify URL and access token.

```

proxyRouter.get("/create-discount-code-auth", async (req, res) => {

// Hard coded Shopify site url and access token but I want this to be dynamic for each store
  const client = new Shopify.Clients.Rest(
    "SHOPIFY_SITE_URL!",
    "SHOPIFY_ACCESS_TOKEN!"
  );

  // Create a new discount code with the Shopify API
  const response = await client.post({
    type: DataType.JSON,
    path: `/admin/api/2022-10/price_rules/1032127185061/discount_codes.json`,
    data: {
      discount_code: {
        code: "TESTTEST",
        usage_count: 1,
      },
    },
  });

  res.status(200).json(response);
});

```


Is there a way I can use:

```
const session = await Shopify.Utils.loadCurrentSession(req, res, false);
const client = new Shopify.Clients.Graphql(session.shop, session.accessToken);
```

**Comment by nzmitch** [comment]
I can find the SHOPIFY_SITE_URL & SHOPIFY_ACCESS_TOKEN in our mongoDB Session Model. This should solve my current issue.

**Comment by kinngh** [comment]
You can get the Shopify url for each store by looking into the headers. I'm on the road right now so I can't respond with code, but just search for "req.header", of console log the req variable on request and get the myshopify url from there. 

I'll post a better solution to this once I'm back on Monday^

**Comment by kinngh** [comment]
You can just use 


const shop = req.header("x-shop-domain");
const session = await Shopify.Utils.loadOfflineSession(shop);
