### ISSUE TITLE
npm run s:e:deploy | ERROR Invalid hook call

### ISSUE THREAD

**Issue by nzmitch** [kinngh/shopify-node-express-mongodb-app#32]
I'm getting this error in my console when running npm run s:e:deploy

` ERROR Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of  
       the following reasons:
       1. You might have mismatching versions of React and the renderer (such as React DOM)
       2. You might be breaking the Rules of Hooks
       3. You might have more than one copy of React in the same app
       See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.`

This command has worked in the past and I haven't made any changes to my theme-app-extension so I'm not sure why it's throwing this error. 

I've tried all these solutions https://bobbyhadz.com/blog/react-invalid-hook-call-hooks-can-only-be-called-inside-body

I'm also not using react in my theme-app-extension, so I'm not sure why this error occurred out of nowhere.

I've cloned this repo to test if it's an issue with my specific app but the same error occurred.

**Comment by kinngh** [comment]
You recon we could hop on a call and I can take a look at what's happening? I'm almost 100% sure this is not an error with the repo itself, but somewhere you've imported a hook and it's throwing errors.

**Comment by kinngh** [comment]
The invalid hook call is because of React version mismatch with `@shopify/app`, `@shopify/cli` and `@shopify/cli-kit`. To get around this, downgrade `react` and `react-dom` to `17.0.2`. Please make sure to remove your `package-lock.json` and `node_modules/` and reinstall if it doesn't work in the first go.

A fix will be up as soon as one is found, supporting React `18.x`

**Comment by kinngh** [comment]
Fixed in [b2535e4](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/b2535e4114562929c47e301998781af413405360). Thank you for flagging this!
