### ISSUE TITLE
App production mode crashed 

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#33]
Error after app reinstalling 

**The app couldn’t be loaded

This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser](https://community.shopify.com/c/Shopify-Apps/Some-Third-Party-Apps-may-not-be-accessible-on-Chrome-80-update/m-p/650220/thread-id/20503), or contacting the developer to get support.**

i run node app after `npm run build`  still the error.  can you help me on that

**Comment by kinngh** [comment]
Are you on the latest build that removes dependencies on cookies?

**Comment by adventuretocode** [comment]
> Are you on the latest build that removes dependencies on cookies? **no** 

i have working code repo date 30 Sep 2022  https://github.com/kinngh/shopify-node-express-mongodb-app/commit/f1a1c8384f8f75794c521687ab33b69b5595acae  this last commit.

app was working fine but now it was giving error i clear the browser cache cookies delete all the data still same Error.

**Comment by kinngh** [comment]
Can I take a look at this? You can setup a time with me [here](https://cal.com/kinngh)

**Comment by kinngh** [comment]
Solution: Update auth flow

**Comment by adventuretocode** [comment]
@kinngh   I  have same issue 
![image](https://user-images.githubusercontent.com/114073623/199219660-c14cbffe-f3d1-4cc4-a291-285eeea239cc.png)

complete code update as per this commit - https://github.com/kinngh/shopify-node-express-mongodb-app/commit/b1202a893df18003103aca0817ed0458a3778253

**Comment by adventuretocode** [comment]
@kinngh  all code is upto date with current repo.
https://shopify.dev/apps/auth/oauth/session-tokens/getting-started does this article outdate ?

**Comment by kinngh** [comment]
Then it's possibly a package, because I don't see this in any of my repos.

**Comment by adventuretocode** [comment]
@kinngh   i have same package.json  i removed the node_modules and package-lock.json  after install node package. 
i contact to shopify patner support team they say auth flow  not properly implemented https://shopify.dev/apps/auth/oauth/session-tokens/getting-started 

how i can debug this issue ?

**Comment by kinngh** [comment]
If it's the same auth flow, there shouldn't be any issues because this auth flow is being used in ~18 production apps + the engineers who use my repo as a base

**Comment by adventuretocode** [comment]
@kinngh  thanks for the answer 
new auth system as per your committed all file i replaced  with code manully copy pasted so no any error in migration.

![Screenshot from 2022-11-02 16-24-47](https://user-images.githubusercontent.com/114073623/199473007-6dcdbba5-65a0-46fb-8b5c-292c3d0346e2.png)

i take pull from your latesh repo i can see vite build on  see above screenshot 

can you suggest me where its breaking i will double check that code.

**Comment by kinngh** [comment]
I can't suggest where things are breaking if I don't have access to the code. Happy to sign an NDA to take a look at this.

**Comment by adventuretocode** [comment]
@kinngh  i will share the private repo with you.  and NDA sharing on your email

**Comment by kinngh** [comment]
Quickly took a look at the code and things seem to be fine with auth, haven't pulled the code yet. I don't have any free hours available and since this is not a repository level issue, happy to extend up to 2 hours of debugging @ $150/hour.

**Comment by adventuretocode** [comment]
> Quickly took a look at the code and things seem to be fine with auth, haven't pulled the code yet. I don't have any free hours available and since this is not a repository level issue, happy to extend up to 2 hours of debugging @ $150/hour.

no thanks
