### ISSUE TITLE
Shopify Polaris Frame Logo Url blocked by CSP

### ISSUE THREAD

**Issue by KlocRanjana** [kinngh/shopify-node-express-mongodb-app#38]
I am using below code in Frame component
const logom = {
    width: 124,
    topBarSource: logo,
    url:"/"
  }
But when I clicked on logo I am getting below error

**Refused to frame 'https://3916-103-136-95-137.in.ngrok.io/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".**

Can you please help me

**Comment by kinngh** [comment]
What is the source of your logo, and can you please add in the entire source for the page so I can understand what I'm dealing with here?

**Comment by KlocRanjana** [comment]
import {
  AppProvider,
  Frame,
  Navigation,
  TopBar,
} from '@shopify/polaris';
import {
  HomeMinor,
  SettingsMinor,
  TransactionMajor, InfoMinor
} from '@shopify/polaris-icons';
import { useState, useCallback, useRef } from 'react';
import ApolloClientProvider from "../providers/ApolloClientProvider";
import { useRoutes, navigate } from "raviger";
import { useAppBridge } from "@shopify/app-bridge-react";
import routes from "../Routes";
import logo from '../assets/logo.png'

const TopBarex = () => {
  const app = useAppBridge();
  const skipToContentRef = useRef(null);
  const [mobileNavigationActive, setMobileNavigationActive] = useState(false);
  const RouteComponents = useRoutes(routes);
  const [selected, setSelected] = useState(false);

  const handleSelect = (selectedId) => {
    setSelected(selected => selected === selectedId ? null : selectedId);
  };

  const toggleMobileNavigationActive = useCallback(
    () =>
      setMobileNavigationActive(
        (mobileNavigationActive) => !mobileNavigationActive,
      ),
    [],
  );


  const logom = {
    width: 124,
    topBarSource: logo,
    url:"/"
  }

  const topBarMarkup = (
    <TopBar
      showNavigationToggle
      onNavigationToggle={toggleMobileNavigationActive}
    />
  );

  const navigationMarkup = (
    <Navigation location="/">
      <Navigation.Section
        items={[
          {
            label: 'Homepage',
            icon: HomeMinor,
            selected: selected === "/",
            onClick: () => {
              handleSelect("/");
              navigate('/');
            },
          },
          {
            label: 'Integration Settings',
            icon: SettingsMinor,
            selected: selected === "/mloyalConfig",
            onClick: () => {
              handleSelect("/mloyalConfig");
              navigate('/mloyalConfig');
            },
          },
          {
            label: 'Loyalty Program Settings',
            icon: SettingsMinor,
            selected: selected === "/adminConfig",
            onClick: () => {
              handleSelect("/adminConfig");
              navigate('/adminConfig');
            },
          },
          {
            label: 'Transactions',
            icon: TransactionMajor,
            selected: selected === "/mloyalTransactions",
            onClick: () => {
              handleSelect("/mloyalTransactions");
              navigate('/mloyalTransactions');
            },
          },
          {
            label: 'Help',
            icon: InfoMinor,
            selected: selected === "/help",
            onClick: () => {
              handleSelect("/help");
              navigate('/help');
            },
          },
        ]}
      />
    </Navigation>
  );

  return (
    <div style={{ height: '500px' }}>
      <AppProvider
        i18n={{
          Polaris: {
            TopBar: {
              toggleMenuLabel: 'Toggle menu',
            },
            Frame: {
              skipToContent: 'Skip to content',
              navigationLabel: 'Navigation',
              Navigation: {
                closeMobileNavigationLabel: 'Close navigation',
              },
            },
          },
        }}
      >
        <Frame
          logo={logom}
          topBar={topBarMarkup}
          navigation={navigationMarkup}
          showMobileNavigation={mobileNavigationActive}
          onNavigationDismiss={toggleMobileNavigationActive}
          skipToContentTarget={skipToContentRef.current}
        >
          <ApolloClientProvider>{RouteComponents}</ApolloClientProvider>
        </Frame>
      </AppProvider>
    </div>
  );
}
export default TopBarex



This is the code I am using

**Comment by kinngh** [comment]
Why is your logo in `assets/` when it should be in `public/`? Please learn how to use React before you jump on to building essential apps.
