### ISSUE TITLE
Trying to query Rest client throws unauthorized error

### ISSUE THREAD

**Issue by Nithur-M** [kinngh/shopify-node-express-mongodb-app#42]
I am trying to get a product from the store like this:

```
const client = new shopify.clients.Rest({ session });
const product = await client.get({
     path: `products/${productId}`,
     query: {id: 1, title: "title"}
});
```
But it is throwing the following error:
```
code: 401,
[server]     statusText: 'Unauthorized',
[server]     body: {
[server]       errors: '[API] Invalid API key or access token (unrecognized login or wrong password)'
[server]     },
```

I am retrieving the session from the mongodb to pass to this function. It is succesfully creating the client. But fails to access the endpoints with the created client. What am I missing here?

**Comment by kinngh** [comment]
Is it possible to share the entire file? I don't usually work with REST so I'm gonna have to check it out properly^

**Comment by Nithur-M** [comment]
the same issue persists with Graphql too. When I try to get the shop name like this, it throws the same error:
```
const client = new shopify.clients.Graphql({session});
const shop = await client.query({
    data: `{
      shop {
        name
      }
    }`,
  });
```

**Comment by Nithur-M** [comment]
For context:
I want to fetch all the session from the mongo to go one by one to fetch each store's product details. And then I pass the `session` object to the graphql to create a client. Client has been successfully created. But the issue is when I try to query the created client.

**Comment by kinngh** [comment]
How are you fetching your `session`?

**Comment by Nithur-M** [comment]
> How are you fetching your `session`?

from mongodb just like `loadSession`

**Comment by Nithur-M** [comment]
> 1. You need to be really descriptive because this isn't helping.
> 2. You have client providers available in `utils/` that work directly with this.
> 
> ```
> import "./utils/clientProvider.js";
> 
> const { client } = await clientProvider.graphqlClient({
>     req,
>     res,
>     isOnline: false,
>   });
> const shop = await client.query({
>     data: `{
>       shop {
>         name
>       }
>     }`,
>   });
> ```
> 
> 3. If you want to use the offline tokens only directly from the db
> 
> ```
> import sessionHandler from "./utils/sessionHandler.js";
> import shopify from "./utils/shopifyConfig.js";
> 
> const offlineSessionId = await shopify.session.getOfflineId({shop});
> const session = await sessionHandler.loadSession(offlineSessionId);
> ```

we have sessions stored in Mongodb, right? I am retrieving them and passing it to Rest/Graphql client like this:
```
const sessions = await sessionHandler.loadAllSession();
sessions.forEach(async session => {
    const client = new shopify.clients.Graphql({session});
    const shop = await client.query({
        data: `{
          shop {
            name
          }
        }`,
      });
```

Here is the code I tried to get the shop name of all the sessions.

**Comment by Nithur-M** [comment]
> const offlineSessionId = await shopify.session.getOfflineId({shop});
in this code, how can I dynamically get the offlineSessionId?
I want to construct a cron job to periodically check certain info about all the stores using my app.
