### ISSUE TITLE
@shopify/cli-kit' does not provide an export named 'api'

### ISSUE THREAD

**Issue by robotshatemonkeys** [kinngh/shopify-node-express-mongodb-app#45]
When running "npm run update:url" 

updateDashboard.js
api as cliAPI
The requested module '@shopify/cli-kit' does not provide an export named 'api'
 "@shopify/cli-kit": "^3.33.0"

**Comment by kinngh** [comment]
Yep this is being worked on. Given this is undocumented, I'm searching for a better fix to take care of this issue. In the meantime, you can update urls directly in the Shopify Partner Dashboard.

**Comment by kinngh** [comment]
Fixed with [`0b3238a`](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/0b3238aafa72e1bdcb2c38fc301c0af2b3c5ea1b)
