### ISSUE TITLE
npm run update:url issue

### ISSUE THREAD

**Issue by charlower** [kinngh/shopify-node-express-mongodb-app#46]
Hey Harshdeep I'm getting this error when trying to run update:url: 

  api as cliAPI,
  ^^^
SyntaxError: The requested module '@shopify/cli-kit' does not provide an export named 'api'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

any idea what could cause this?

**Comment by charlower** [comment]
Oh looks like they removed api from cli-kit since your video

**Comment by charlower** [comment]
they removed it in this version: 

https://www.npmjs.com/package/@shopify/cli-kit/v/3.33.0?activeTab=explore

**Comment by charlower** [comment]
next error I got was: 

Cannot read properties of undefined (reading 'request')
    at getOrgs (file:///Users/charlie/jotbot/devUtils/updateDashboard.js:25:42)
    at selectOrg (file:///Users/charlie/jotbot/devUtils/updateDashboard.js:19:22)
    at file:///Users/charlie/jotbot/devUtils/updateDashboard.js:95:7
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Downgraded to 3.25 and its now working

**Comment by kinngh** [comment]
An update to this was pushed in the last commit - [`0b3238`](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/0b3238aafa72e1bdcb2c38fc301c0af2b3c5ea1b). You can update `@shopify/cli-kit` to the latest version and use the updated script instead.

**Comment by charlower** [comment]
cool thanks a lot
