### ISSUE TITLE
There’s no page at this address when installing the app via Shopify Partners

### ISSUE THREAD

**Issue by 0thmane** [kinngh/shopify-node-express-mongodb-app#48]
Hello, 

Thank you so much for your effort to build this repository.

I am new in shopify app developement, i am trying to learn & understand how shopify app works.

I want to fix a problem but i don't know how to fix it. When i try to install the app via url : https://ngrockurl/auth?shop=${shop}, it works & redirect to the installation page shopify (below screenshot)
![image](https://user-images.githubusercontent.com/26823650/215348330-c04050de-8320-4cc3-8d76-ec1188aaf2cf.png)

But when i try to install the app using the shopify partner, i have this error 'There’s no page at this address' (below screenshot)
![image](https://user-images.githubusercontent.com/26823650/215348446-69f84a8c-749d-4072-a63b-ccf1ac4bd8d3.png)

I launch the application test in a test store using the shopify partners dashboard like this (below screenshot)
![image](https://user-images.githubusercontent.com/26823650/215348528-39dfa1ad-4713-4616-acf4-a537278a72f9.png)

It's like they try to launch the '/' (Index component of react) but the app is not installed yet in the store, and there no redirection to /auth or something like that. 
Can you help me with a hint to fix it please ?

Thank you so much

**Comment by kinngh** [comment]
Thank you for flagging this! I'm working on a fix and deploying^

**Comment by kinngh** [comment]
Looks like this is in dev mode only because Vite doesn't pass through middlewares. This will still be fixed, but it has no impact on production so we're good to go.

**Comment by kinngh** [comment]
Pinning this issue. 

`This has no impact on production.`

In Dev mode, use the ngrok url install method instead of using Shopify partners page. This is because Vite and Express are being served from two different ports and running Vite directly skips middleware checks from Express, causing the app to not check for auth before showing the UI. This is a dev mode only bug and is currently being worked on^

**Comment by 0thmane** [comment]
Yes, Thank you so much for the clarification.
