### ISSUE TITLE
Vite HTTP proxy error

### ISSUE THREAD

**Issue by c-sull** [kinngh/shopify-node-express-mongodb-app#49]
Hi! I've been following through your tutorial on YouTube to get a feel for how everything works, but am running into an issue hosting the server. I've followed all the steps through to 40:53 on the video, but when I try adding the app to my dev shop I'm running into a 500 internal server error. My steps to start it are as follows:

Start mongo (`mongod --dpbath mongo`)
Run ngrok, copy ngrok.io link to SHOPIFY_APP_URL
Run `npm run update:url`
Verify url's are updated in Shopify partner page
Run `npm run dev`

When I go to `localhost:4040` it displays each attempt as `GET /auth | 500 Internal Server Error | <time>`, and in the `npm run dev` console each attempt displays the message:
 `[vite] http proxy error at /auth?shop=<shop name>.myshopify.com:
[client] Error: connect ECONNREFUSED 127.0.0.1:8081
[client]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)`

Any help would be much appreciated!

**Comment by kinngh** [comment]
You cannot access it locally. Instead, try `https://ngrokurl/auth?shop=shopname.myshopify.com` to get it working.

**Comment by c-sull** [comment]
Update: fixed the issue. I was missing an error in the CLI stating `"NODE_ENV" is not recognized as an internal or external command, operable command or batch file`. Fixed the issue by running `npm install -g win-node-env` per [this stackoverflow post](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman). Not sure if I just had a weird setup, but running that fixed it for me on Windows.

**Comment by c-sull** [comment]
> You cannot access it locally. Instead, try `https://ngrokurl/auth?shop=shopname.myshopify.com` to get it working.

That's how I was testing it originally, but I guess I didn't explain it correctly. Whenever I would go to `https://ngrokurl/auth?shop=shopname.myshopify.com` it would show me a blank page (or an ngrok 8012 error), and I was able to see it was a 500 error by connecting to localhost:4040

**Comment by kinngh** [comment]
Can you upload a screencast?

**Comment by kinngh** [comment]
This is a known issue on Windows^

**Comment by kinngh** [comment]
Added note in `SETUP.md` [fcee97a79aef5d9b97b5e12f6615ab01b2d3230d](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/fcee97a79aef5d9b97b5e12f6615ab01b2d3230d)
