### ISSUE TITLE
npm run s:e:create - ERROR  Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by ws3li** [kinngh/shopify-node-express-mongodb-app#54]
Hello,

Is anyone having an issue with `npm run s:e:create`?

I encountered the following error: 
![image](https://user-images.githubusercontent.com/6070457/217137503-b8573476-f288-4a11-ab78-bf81d8390fce.png)

I can build and run the project with no problem, but when I try to run the command: `npm run s:e:create` to create a theme app extension in the project I got the error above.

I am using the latest project with the latest dependencies.
- I am on a Windows machine and have set up local MongoDB using the local folder method
- Shopify is working and I can see the store with my app
- I have not made any modification other than following the "setup steps" to get things started

I am fairly new to Shopify App development, any help will be greatly appreciated. Thanks in advance!

**Comment by kinngh** [comment]
Run `npm ls react` to see if there's any clashes with React versions. You can then either override those with versions of React in your `package.json` or downgrade React to `17.x.x`. Though it is highly recommended to just create a new folder outside your project with an empty `shopify.app.toml` and filled out `.env` file to create extensions.
