### ISSUE TITLE
[shopify-api/ERROR]  Invalid OAuth callback. 

### ISSUE THREAD

**Issue by zeeshanalimughal** [kinngh/shopify-node-express-mongodb-app#55]
Hey Harshdeep hope you are fine,
I am getting this error

"--->Error at /auth/tokens InvalidOAuthError: Invalid OAuth callback."

This error occurs when I try to install the app on two stores of same account at same time. When I click on install button of first store then second store simultaneously. This error comes on one of them as the other store successfully install the app. Also some times this error accours while installing on one single store also. 

I am working on first shopify project to learn shopify app development.
I want to fix this. Do you have any idea what could cause this error?

**Comment by kinngh** [comment]
I'm using this in production and we haven't run into any invalid OAuth callbacks just yet. Have you tried pushing it on a server and trying if you can replicate this?

**Comment by zeeshanalimughal** [comment]
Yes I have tried on production also it sometimes show that error. But after one or two times after facing this error, the app was install successfully. So on production also this wrror occurs occasionally.

**Comment by kinngh** [comment]
Putting this under investigation

**Comment by zeeshanalimughal** [comment]
Thank you!

**Comment by kinngh** [comment]
@zeeshanalimughal where are you hosting the Server and DB in production mode?

**Comment by zeeshanalimughal** [comment]
On Heroku and Db is from MongoDb Atlas.

**Comment by kinngh** [comment]
Can't replicate it. Can you change your `utils/shopifyConfig.js` to the following snippet and email me the log at info (at) heuramedia (dot) com?

```javascript
import { LogSeverity, shopifyApi } from "@shopify/shopify-api";
import "dotenv/config";

// Setup Shopify configuration
const shopify = shopifyApi({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET,
  scopes: process.env.SHOPIFY_API_SCOPES,
  hostName: process.env.SHOPIFY_APP_URL.replace(/https:\/\//, ""),
  hostScheme: "https",
  apiVersion: process.env.SHOPIFY_API_VERSION,
  isEmbeddedApp: true,
  logger: { level: LogSeverity.Debug },
});

export default shopify;

```

**Comment by zeeshanalimughal** [comment]
Yes I have send mail with logs.

**Comment by harrynimz** [comment]
I had the same problem. Forgot to set a SHOPIFY_API_VERSION in .env - not it works. Thanks @kinngh for this great template!

**Comment by kinngh** [comment]
@zeeshanalimughal actually now that I see, is your setup check passing successfully and can you share your env file with your api key and secret blurred?

**Comment by kinngh** [comment]
@harrynimz glad you like it!

**Comment by zeeshanalimughal** [comment]
<img width="684" alt="screenshot" src="https://user-images.githubusercontent.com/76431704/220101906-eb304a79-fd64-48f0-a16a-9a85a9c3e863.PNG">

**Comment by kinngh** [comment]
Remove the PORT value from your env

**Comment by zeeshanalimughal** [comment]
<img width="784" alt="Capture" src="https://user-images.githubusercontent.com/76431704/220136702-57ed7329-e7f8-49cb-8063-0548cb3d9bdb.PNG">

Still same error.

**Comment by kinngh** [comment]
So I saw your logs, we can only replicate this in MongoDB and never when using Prisma + SQL databases. Though I have a few apps running this with MongoDB on production, we're not running into this error, and it's not replicable. This is potentially some error in your setup because across multiple production and dev apps, this is not replicable.

Marking this as closed^

**Comment by zeeshanalimughal** [comment]
Thanks @kinngh
