### ISSUE TITLE
hmac timestamp is outside of the tolerance range

### ISSUE THREAD

**Issue by kmajay978** [kinngh/shopify-node-express-mongodb-app#58]
After successfully app installation. It display blank white screen with following message.
**hmac timestamp is outside of the tolerance range**
![image](https://user-images.githubusercontent.com/75435942/220603801-0935be23-4c8c-4b71-9de2-61a26dd8cd4f.png)

**### Second Issue**

After running this command :- npm run update:url

**Note:-** I do have already installed the node modules

> shopify-express-boilerplate@0.0.6 update:url
> node devUtils/updateDashboard.js

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\Shopify app\order\node_modules\@shopify\cli-kit\dist\index.js' imported from E:\Shopify app\order\devUtils\updateDashboard.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**System :-** Windows 10
**Node version:-**  v18.14.1

**Comment by kinngh** [comment]
`HMAC tolerance` this is the first time I'm seeing this issue and is unheard of. Is there a reliable way to replicate this issue?

`npm run update:url` is usually a hit or miss, as stated in comments in the `updateDashboard.js` file since it uses undocumented APIs to get things done.

**Comment by kmajay978** [comment]
Regards HMAC tolerance, I don't have any idea. Around 1 month back, everything was working fine. 

Today, I cloned the repository and setup the project, after that I got this issue.

**Comment by kinngh** [comment]
I haven't been able to replicate the issue, but if it happens again can you upload the log too?

**Comment by kmajay978** [comment]
Hi @kinngh , Kindly check, here **what i got in logs**

````````````````

[server] [shopify-api/INFO] Beginning OAuth | {shop: testhubfinal.myshopify.com, isOnline: false, callbackPath: /auth/tokens}
[server] [shopify-api/DEBUG] OAuth started, redirecting to https://testhubfinal.myshopify.com/admin/oauth/authorize?client_id=346c080303b0a7c06ae69ec4728b2784&scope=write_themes%2Cwrite_script_tags&redirect_uri=https%3A%2F%2Fc8cd-2401-4900-5978-edad-1d8a-6c16-4ab5-ee97.in.ngrok.io%2Fauth%2Ftokens&state=813507951337385&grant_options%5B%5D= | {shop: testhubfinal.myshopify.com, isOnline: false}
[server] [shopify-api/INFO] Completing OAuth | {shop: testhubfinal.myshopify.com}
[server] ---> Error at /auth/tokens InvalidHmacError: HMAC timestamp is outside of the tolerance range
[server]     at validateHmacTimestamp (E:\Shopify app\shopify-node-express-mongodb-app\node_modules\@shopify\shopify-api\lib\utils\hmac-validator.js:45:15)
[server]     at E:\Shopify app\shopify-node-express-mongodb-app\node_modules\@shopify\shopify-api\lib\utils\hmac-validator.js:31:9
[server]     at Generator.next (<anonymous>)
[server]     at E:\Shopify app\shopify-node-express-mongodb-app\node_modules\tslib\tslib.js:167:75
[server]     at new Promise (<anonymous>)
[server]     at Object.__awaiter (E:\Shopify app\shopify-node-express-mongodb-app\node_modules\tslib\tslib.js:163:16)
[server]     at E:\Shopify app\shopify-node-express-mongodb-app\node_modules\@shopify\shopify-api\lib\utils\hmac-validator.js:27:31
[server]     at E:\Shopify app\shopify-node-express-mongodb-app\node_modules\@shopify\shopify-api\lib\auth\oauth\oauth.js:124:66
[server]     at Generator.next (<anonymous>)
[server]     at E:\Shopify app\shopify-node-express-mongodb-app\node_modules\tslib\tslib.js:167:75

**Comment by kmajay978** [comment]
It seems, we have an issue from shopify end. Let me know your toughts regarding this. I commented the shopify.auth.callback , it does not go to catch block otherwise, everytime it goes into catch block. 

![image](https://user-images.githubusercontent.com/75435942/220840963-09f6c789-5fe8-417c-afd3-4f63671d20c3.png)

**Comment by kinngh** [comment]
This looks like an issue with the Shopify package. Can you try out with the official cli and see if you can replicate it?

**Comment by kmajay978** [comment]
Ok, I will check with shopify cli.

**Comment by pinalzala** [comment]
I'm also facing same issue
node:internal/errors:490
ErrorCaptureStackTrace(err);
^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Shopify\order\node_modules@shopify\cli-kit\dist\index.js'

**Comment by kinngh** [comment]
@pinalzala this is a recurring issue now, it's been very clearly stated in the `devUtils/updateDashboard.js` file that it may break in future because we're using undocumented APIs.

Ref: https://github.com/kinngh/shopify-node-express-mongodb-app/blob/9cf2c872c5914777445f10cd2b83a8ec4d218a1c/devUtils/updateDashboard.js#L8

**Comment by kinngh** [comment]
Update URL is now fixed with [99d533a](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/99d533a7f076a5ebb4741df0857ccd8b9f9572ed) . Make a git pull to update your project.

**Comment by kmajay978** [comment]
Hello @kinngh , 

After looking into to doc, i figured out the solution. one thing comes to mind - The [HMAC validation code mentions 90 seconds as the tolerance limit](https://github.com/Shopify/shopify-api-js/blob/21696ab6a5de1b78859421746164f1fbcea7a281/lib/utils/hmac-validator.ts#L53), any chance your computer's local clock is off by more than 90 seconds?

All we need to do is to sync our computer clock to the latest time.

**Comment by kinngh** [comment]
Firstly, the issue was on your end not mine, and I couldn't replicate it at all. Secondly, glad you have this figured out!
