### ISSUE TITLE
CSP rejected by shopify team. 

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#61]
App rejected notice. 
App must set security headers to protect against clickjacking.
To prevent clickjacking attacks, your app must set the [proper content security policy directive](https://shopify.dev/apps/store/security/iframe-protection). If your app is not embedded in an Iframe in the Shopify admin, and you are seeing this message, check your app's settings and make sure it is set to "non-embedded." If your app is embedded, then we expect the 'Content-Security-Policy' header to be frame-ancestors https://admin.shopify.com/ https://[shop].[myshopify.com](http://myshopify.com/), where [shop] is dynamically set to the shop domain the app is embedded on.

my app code with repo https://github.com/kinngh/shopify-node-express-mongodb-app/commit/93fbd7adf09c1f724fb65a2ced347a0a099fe952

i can see the CSP new update . https://github.com/kinngh/shopify-node-express-mongodb-app/commit/3e4bedb5b178b90d4ddc884bce9875577828793d

old code  has same CSP header value.

app  CSP network tab set into the header.
![git csp 2](https://user-images.githubusercontent.com/114073623/221492999-f9a65490-0b6a-40e0-a18b-93e0d1f0e2f6.png)

**Comment by kinngh** [comment]
There was a recent commit that updated how CSP is handled and was switched to the `verifyRequest` middleware.

**Comment by adventuretocode** [comment]
@kinngh  Thanks lot. I have update the code with same https://github.com/kinngh/shopify-node-express-mongodb-app/commit/3e4bedb5b178b90d4ddc884bce9875577828793d
 app get rejected again with same error message received from the shopify review team.

**Comment by kinngh** [comment]
I've never seen a CSP rejection on my boilerplate. What I do suspect is you have multiple CSP headers, as in your screenshot, that you need to deal with. The scope of issues here is the repo, not your personal code.

**Comment by SzuJanLin** [comment]
Is there any update on this issue? I received the same error on Shopify. Couldn't find out what I did wrong and where I did wrong and my code base is the same as the template.

**Comment by kinngh** [comment]
I've had 0 CSP issues. Is it possible to take a look at your codebase?

**Comment by kinngh** [comment]
DM me on Twitter at twitter.com/kinngh

**Comment by kinngh** [comment]
Digging further, why does your CSP has the `self` in it? here's my CSP string:
![Screenshot 2023-04-08 at 4 16 38 PM](https://user-images.githubusercontent.com/773555/230717117-9924828b-6ca2-47b4-a61d-21df9cea7547.png)


It's clear that you're messing with the CSP strings and then running into issues with app rejection.
