### ISSUE TITLE
Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by rkmicrasolution** [kinngh/shopify-node-express-mongodb-app#63]
![Screenshot 2023-02-28 093200](https://user-images.githubusercontent.com/121227808/221750506-7b6cfc3a-d228-4c66-94c9-a5cbd407429b.png)

We are trying to use API calling but still facing the problem. Can you please give me example? how to resolve this?.

**Comment by kinngh** [comment]
The scope on issues for this repo is for the boilerplate only. To use React Query please read the docs.
