### ISSUE TITLE
Recent i update the code as per lasted code.  getting Error for session not load. 

### ISSUE THREAD

**Issue by adventuretocode** [kinngh/shopify-node-express-mongodb-app#64]
@kinngh  Thank for the update date this code boilerplate. 
i was facing some issue with old user who has app already app installed. for those store app was not loading. 
i can see the this server side log as per beloved mention.
` 

 SessionStorageError: CustomSessionStorage failed to load a session. Error Details: Error: Unsupported state or unable to authenticate data
         |     at SessionStorageError.ShopifyError [as constructor] ( /node_modules/@shopify/shopify-api/dist/error.js:13:28)
         |     at new SessionStorageError ( /node_modules/@shopify/shopify-api/dist/error.js:206:42)
         |     at CustomSessionStorage.<anonymous> ( /node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:51:31)
         |     at step ( /node_modules/tslib/tslib.js:144:27)
         |     at Object.throw ( /node_modules/tslib/tslib.js:125:57)
         |     at rejected ( /node_modules/tslib/tslib.js:116:69)
         |     at processTicksAndRejections (node:internal/process/task_queues:96:5

`

after force fully hit the /auth url app is working fine.

**Comment by kinngh** [comment]
Ya this seems to happen with MongoDB specifically sometimes. Though very rare, I don't know of a good way to replicate this. The next time if this happens, just delete the sessions and it'll force auth the user.

**Comment by adventuretocode** [comment]
@kinngh  This was the still issue any suggestion how I can fix it?

**Comment by kinngh** [comment]
try/catch this. If your `e.message` lines up with this, reauth the user. No other way to properly deal with this as far as I know
