### ISSUE TITLE
Working with theme extension, Giving 404 error while fetching data from database to theme extension.

### ISSUE THREAD

**Issue by kmajay978** [kinngh/shopify-node-express-mongodb-app#65]
First of all thanks for the package, first time i am working with your package. Recently, i created an extension, now i am trying to send the product id along with shop name. And wants to retrieve the data from database and set in local storage. 

I have created the route for getting the data, but it's returning 404 not found. I am not getting the issue. As other admin routes working fine but when i am trying to access the get-frontend-product on storefront. it throw error 404

**Error:-** https://prnt.sc/ufd8NYe-sATV

**Here is my theme extension code**
```
  $.ajax({
                method: "POST",
                url: `https://d16d-2405-201-5003-ae2d-785e-446b-9992-c22d.in.ngrok.io/api/get-frontend-product`,
                cache: false,
                headers: {
                    "Content-Type": "application/json",
                  },
                data: { shop: shopUrl, productId:product_id},
                success: function (response) {
                    local_set('vdata',response);
                    console.log(response,'response..............');
                }
            })
```

**Routes**

```
userRoutes.post("/api/get-frontend-product", async (req, res) => {
  let frontProduct = await getFrontendProduct(req,res);
  if (frontProduct) {
    res.status(200).send({frontProduct,success:true});
  } else {
    res.status(403).send("An error occured");
  }
});
```

KIndly help me out, why it's not working, other api route working fine for admin side. But i am trying to work with theme app extension to work with store. Help would be appreciated. 

Thanks

**Comment by kinngh** [comment]
1. Please read the docs. 
2. The issues here are only for the repo and not personal help topics.
