### ISSUE TITLE
Trouble with API calls - most certainly user error. 

### ISSUE THREAD

**Issue by ohermans1** [kinngh/shopify-node-express-mongodb-app#66]
Hey mate, 

First of all, thanks so much for this template and for all the work you've put in. I've got it mostly up and running on my machine. I'd say you can certainly preemptively mark this issue as 'user error' haha. 

Basically, I'm just having trouble with my API calls. I apologize for reaching out, but I've been trying for a good few days and just cannot work it out!

Are you able to take a look at my screenshots below and let me know if I'm missing something obvious?

My env
![image](https://user-images.githubusercontent.com/50157976/225565382-23870253-8b64-4611-b6b3-78f4a46468e2.png)

My index.js
![image](https://user-images.githubusercontent.com/50157976/225566388-b8bfe23b-2610-431c-afa9-f776909f9d3f.png)

My getData.js
![image](https://user-images.githubusercontent.com/50157976/225566654-1ff3cc1b-5706-404e-8a7c-d4d6de0d38b4.png)

My console response:
![image](https://user-images.githubusercontent.com/50157976/225567165-58e538ea-d9fc-429b-9fce-eb5598b755ee.png)

and finally, my terminal response from my npm run dev (this all runs fine until the request happens). 
![image](https://user-images.githubusercontent.com/50157976/225567676-d7fa1da5-6713-4946-8c4b-fd3f95ff64ab.png)

Also, goes without saying, but if you can't be bothered looking at all this, just tell me to piss off and mark this as resolved haha! You've done enough just making the template.

**Comment by kinngh** [comment]
Thank you for the kind words! 

I just looked into this; It's partly my fault too that I ignored how the REST client actually works. I've pushed a new [commit](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/88125b117cefa839d0f9c82f6cf3c409cae73b3f) that fixes how REST client is created and it works now. The issue on your end was you weren't passing the path correctly. Here's the fix for that:


```javascript
userRoutes.get("/api/rest-test", async (req, res) => {
  const {client} = await clientProvider.restClient({ isOnline: false, req, res });
  const data = await client.get({ path: "blogs" });
  console.log(data.body.blogs)
  res.status(200).send({ blogs: data.body.blogs });
});
```

**Comment by ohermans1** [comment]
Oh wow! Thanks so much for the quick response. I'm somewhat glad that is wasn't 100% user error haha. 

I'll give this a go after work! 

Thanks again for everything!
