### ISSUE TITLE
Model.findOneAndUpdate is not a function - Once again user error

### ISSUE THREAD

**Issue by ohermans1** [kinngh/shopify-node-express-mongodb-app#67]
Hey mate,

Thanks so much for your help a few days ago, and I'm sorry for pestering you again (last time I promise). Feel free to just ignore me and mark this as solved if you can't be bothered responding haha.

Basically, I'm trying to add some content to MongoDB. 

I can see that your inbuild models are connecting up with no issues:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/50157976/226150247-03431d99-7ecf-40cc-a458-9ce3fe0571c1.png">

I created a new model, based of your original ones:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/50157976/226150410-70b13ee3-b691-4afd-8009-9c278937a8b2.png">

Then I run it as per your models as well (using findOneAndUpdate)
<img width="340" alt="image" src="https://user-images.githubusercontent.com/50157976/226150459-a9ab1f57-0dad-4bbe-b2a5-219f3fb74a5c.png">

But, for some reason I get the following error:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/50157976/226150478-fbb5fe75-aadb-4707-b2bd-e82356d59c5a.png">

Do you have any tips or tricks? I'm imagining there is something simple I'm missing here!

**Comment by kinngh** [comment]
Are you trying to run mongoose on react side of things? If yes, please, and don't take this lightly, go back to tutorials and understand why you shouldn't be making database calls directly from your frontend and it should be from your server instead.
