### ISSUE TITLE
OAuth flow does not work in dev / production

### ISSUE THREAD

**Issue by marcdelalonde** [kinngh/shopify-node-express-mongodb-app#70]
Hey there,

First of all, thanks a lot for this code starter !

I experience some issue in **dev** and **production** concerning the redirection for the OAuth.

- In **development**, I can see in the console the `[shopify-api/DEBUG] OAuth started, redirecting to ....` notice, but no redirect is happening. And in the chrome console `Refused to frame 'https://test-dev.myshopify.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

- In **production** I have the following error in the chrome console:

`Refused to display 'https://test-app-staging.myshopify.com/' in a frame because it set 'X-Frame-Options' to 'deny'.` like the redirection is made on the backend side instead of the frontend.

Can you help me with that ?

Thanks a lot

**Comment by kinngh** [comment]
Is the app set to embedded? Otherwise the `frame-ancestors` won't be set to `deny`

**Comment by marcdelalonde** [comment]
Yes for sure

<img width="550" alt="image" src="https://user-images.githubusercontent.com/5658057/227726164-25ebd03c-cdcb-49e8-9795-5420ac658962.png">

Even when i remove `res.setHeader("Content-Security-Policy", "frame-ancestors 'none';");` from csp.js, i have the same error. I dont have any other plugin connected or whatever.

**Comment by kinngh** [comment]
DM me on [Twitter/](https://twitter.com/kinngh), let's hop on a call.

**Comment by marcdelalonde** [comment]
Hey @kinngh,

I finally found the problem on my side. You can find below what i changed in the isShopActive.js file:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/5658057/227729350-328640cc-8588-43e1-aea5-bdd0f35b8b68.png">

I added a check before entering in the shop verification, if the path is /exitframe I skip this step as i want the request to reach the express router that display my front app.

Secondly, i added the embedded query params in the redirect request, because it was lost during this redirection.

**Comment by kinngh** [comment]
With stock config, works as expected, changing config like you described is why you're having the unintended results^
