### ISSUE TITLE
`npm run update:url` is broken: Cannot fetch access tokens

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-node-express-mongodb-app#72]
I Harshdeep. The app has suddenly stopped updating URLS. It stops at Fetching access token. I have tried on a fresh clone and it still doesn't work.

**Comment by kinngh** [comment]
Yeah I just saw that too, being actively worked on. For now, you can update the URLs manually

**Comment by kinngh** [comment]
This throws a `502` so pretty sure a CDN is just having a temporary issue^
 `The introspection endpoint returned a 502: https://accounts.shopify.com/oauth/introspection `

**Comment by kinngh** [comment]
This is fixed. If it doesn't work, run `shopify auth logout` and then run `npm run update:url` again. This should prompt you to login again and it'll work as expected.
