### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by mberreth** [kinngh/shopify-node-express-mongodb-app#73]
After completed setup and getting my app to install in my test store I am getting an error when trying to verify my proxy URL.

Following the setup doc I am hitting https://your-url/proxy_route/json where I am replacing your-url with my ngrok URL. The following is displayed in the browser. Looking at the code it seems to be expecting some query parameters.

```
TypeError: Cannot read properties of null (reading 'replace')
    at verifyProxy (file:///Users/mike/tail/server/middleware/verifyProxy.js:7:6)
    at Layer.handle [as handle_request] (/Users/mike/tail/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mike/tail/node_modules/express/lib/router/index.js:328:13)
    at /Users/mike/tail/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/mike/tail/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/mike/tail/node_modules/express/lib/router/index.js:280:10)
    at isShopActive (file:///Users/mike/tail/server/middleware/isShopActive.js:7:5)
    at Layer.handle [as handle_request] (/Users/mike/tail/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mike/tail/node_modules/express/lib/router/index.js:328:13)
    at /Users/mike/tail/node_modules/express/lib/router/index.js:286:9
```

 If I add any parameters like ?xyz I get an unauthorized message. The signatures don't match so verifyProxy is sending a 401.
 
 I've run through setup multiple times and I'm confused why the verifyProxy is expecting query parameters but in the setup it says to test the proxy by simply entering the base URL

**Comment by mberreth** [comment]
Also if I try to hit the proxy sub-path https://tailorie-test-store.shopify.com/apps/express-proxy the browser displays {"errors":"Not Found"}

<img width="636" alt="Screen Shot 2023-04-05 at 2 21 00 PM" src="https://user-images.githubusercontent.com/79154505/230183355-4d940271-3026-4eb2-9b89-a4ef5ceab1f6.png">

**Comment by mberreth** [comment]
When I visit https://tailorie-test-store.myshopify.com/apps/express-proxy/json

I get the ngrok browser warning and clicking the visit site does nothing.

**Comment by kinngh** [comment]
1. Is your env setup properly
2. Can you console log `req.query` in `verifyProxy`?

**Comment by mberreth** [comment]
If I force my way past verifyProxy
<img width="566" alt="Screen Shot 2023-04-05 at 3 18 56 PM" src="https://user-images.githubusercontent.com/79154505/230200659-53a69444-2d68-488c-8793-49ef440fe79f.png">

And add ?xyz to the URL https://blah-blah-blah.ngrok.io/proxy_route/json?xyz
I get a 500 error 
<img width="649" alt="Screen Shot 2023-04-05 at 3 20 38 PM" src="https://user-images.githubusercontent.com/79154505/230201020-6144522c-395b-4458-ac7f-3e6acfa6d682.png">

**Comment by mberreth** [comment]
ngrok is showing me the following in the terminal

HTTP Requests                                                                   
-------------                                                                   
                                                                                
GET /proxy_route/json          500 Internal Server Error                        
GET /proxy_route/json          500 Internal Server Error                        
GET /favicon.ico               304 Not Modified                                 
GET /proxy_route/json          401 Unauthorized                                 
GET /proxy_route/json          500 Internal Server Error

**Comment by kinngh** [comment]
1. Is your env setup properly
2. Can you console log `req.query` in `verifyProxy`?
@mberreth

**Comment by mberreth** [comment]
Hi Kinngh!

Thanks for respoding. I added a console.log in verifyProxy right after the declaration

const verifyProxy = (req, res, next) => {
  console.log(req.query);

When I hit this URL( I restarted ngrok and updated my URLs in the partner admin( I don't get anything in the console.
https://a9e2-140-186-197-52.ngrok.io/proxy_route/json

<img width="1391" alt="Screen Shot 2023-04-05 at 3 29 14 PM" src="https://user-images.githubusercontent.com/79154505/230203352-f85ceec2-ed82-4d14-a992-365ef4a0d707.png">

**Comment by mberreth** [comment]
<img width="864" alt="Screen Shot 2023-04-05 at 3 31 17 PM" src="https://user-images.githubusercontent.com/79154505/230204217-4bda5f96-d761-4753-9176-177d5bc726a5.png">

API keys I got from my partner admin here
<img width="599" alt="Screen Shot 2023-04-05 at 3 32 24 PM" src="https://user-images.githubusercontent.com/79154505/230204604-366ee7fb-2ac9-43cd-ab97-27d040d86d9b.png">

**Comment by mberreth** [comment]
If I pass req.query instead of the 401 status I can see the parameter from my address bar

 if (calculatedSignature === signature) {
    res.locals.user_shop = req.query.shop;
    next();
  } else {
    //res.sendStatus(401);
    res.send(req.query);
  }
  
  But nothing in the console, even with console.log(req.query) still in place above.
<img width="554" alt="Screen Shot 2023-04-05 at 3 37 30 PM" src="https://user-images.githubusercontent.com/79154505/230206024-0d78bf5d-e02d-4ec7-af52-65cdb5c02af5.png">

That is all I can think to share right now. Thanks again for your attention on this.

**Comment by kinngh** [comment]
I want you to write `console.log(req.query)` right after `const verifyProxy = (req, res, next) => {` like you did and send me the console log. The log won't show up on frontend since this is running on the server.

**Comment by mberreth** [comment]
I ran it twice. Once with your username with req.query concatenated to it to prove to myself it was working and then with just req.query

<img width="556" alt="Screen Shot 2023-04-05 at 4 34 35 PM" src="https://user-images.githubusercontent.com/79154505/230217222-b263ffe7-6078-46a2-a8cd-ab14cc35948e.png">

**Comment by kinngh** [comment]
Can you DM me on [Twitter](https://twitter.com/kinngh) so we can hop on a call and I can see what's actually happening?

**Comment by kinngh** [comment]
Fixed: User config error
