### ISSUE TITLE
Shopify app

### ISSUE THREAD

**Issue by ea-soufian** [kinngh/shopify-node-express-mongodb-app#75]
When I start the Shopify app using ngrok, dev mode, and update URL, the Shopify app gets started. However, it keeps refreshing the whole time, even though I didn't change the code.

**Comment by kinngh** [comment]
Can you quickly check if there's multiple copies of the `vite config` file being made? That could explain the issue. If not, happy to hop on a call and see how to reproduce this bug and deploy a fix

**Comment by ea-soufian** [comment]
Hi there! I've checked and can confirm that multiple copies of the vite config file are not being created. If that's not the issue, I'd be happy to hop on a call with you tomorrow to further investigate this bug and work on a solution. Let me know if that works for you!

**Comment by kinngh** [comment]
Sure thing! Can you please DM me on [Twitter](https://twitter.com/kinngh) and we can setup a call?

**Comment by kinngh** [comment]
No response, marking as complete until this is a recurring issue
