### ISSUE TITLE
CANT INSTALL CUSTOM  APP

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-node-express-mongodb-app#77]
Hi, I have developed an app which is a single merchant app but when I try to install it using appurl/auth?shop=shopurl it doesn't let  me install the app. It seems that I am able to install the app in a non transferable store. 

![captureawdawd](https://user-images.githubusercontent.com/125876495/235302235-95d27433-af9e-4a9f-a639-0eae6dabcf2d.png)

**Comment by kinngh** [comment]
this repo only deals with problems around the template and not with Shopify. Please refer to the Shopify Development docs.

**Comment by Hamzakdev112** [comment]
I actually figured it out. Thank you
