### ISSUE TITLE
Issue facing while deploying on production

### ISSUE THREAD

**Issue by yedladinesh** [kinngh/shopify-node-express-mongodb-app#78]
Hi Harshdeep,

I'm facing an issue while deploying on production. And I am using digitaloccean(Ubuntu 20.04). Could please help me out. 

I tried the following steps.
1. I deployed whole project into live server.
2. I run the npm install -f
3. Then, run the npm run build
4. After that, npm run start
5. I given the all permission, still I am getting the issue.

Here's the screenshot

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/52268507/edc665b0-5049-4d61-b8e5-d096aff34939)

It's working fine in local system(Windows 10). It'll much better if you provide me the steps to deploy to the live server. It'll be beneficial for the other user of this package(For future users as well).

Looking forward to your response.

Thanks

**Comment by kinngh** [comment]
I have never deployed it on Digital Ocean so this is new to me too. Give me another day or two and let me deploy it myself and write a guide on it!

**Comment by yedladinesh** [comment]
> I have never deployed it on Digital Ocean so this is new to me too. Give me another day or two and let me deploy it myself and write a guide on it!

Thanks, I appreciate your effort to try this out on your end. I will also try to deploy it myself and see if I can find any solutions.

**Comment by yedladinesh** [comment]
I have solved the issue from my end. Thanks!

**Comment by kinngh** [comment]
...can you add in more info about it?

**Comment by adventuretocode** [comment]
@kinngh  your app setup guide was working for all the Linux based OS. i don't think you need you add particular  platform wise

**Comment by kinngh** [comment]
I just need more info on it so I can add in deployment notes for Docker. Besides, it's really super rude to just respond with `lol i got it working thanks` and drop in no notes because 
1. It's open source
2. You benefit off this work without adding any value to others who might end up having the same problem

**Comment by kleczekr** [comment]
I've recorded a quick screenshare on deployment on a DO droplet:

https://www.loom.com/share/a941a83a72a14432acb36818e689e736

I recommend this article:

https://medium.com/@chris.geelhoed/how-to-deploy-node-js-shopify-apps-to-digital-ocean-4b2350840080

A few things changed with how some things are now installed on DO droplets, but these are easy to find in Digital Ocean documentation.
