### ISSUE TITLE
Target origin vs. Recipient Window Origin

### ISSUE THREAD

**Issue by willmclellarn** [kinngh/shopify-node-express-mongodb-app#8]
Hey man! I'm strangely getting this error sometimes when I exit and re-enter the app url from the merchant's side.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://light-heads-tickle-67-176-66-51.loca.lt') does not match the recipient window's origin ('https://bis-test-cecom.myshopify.com').

Any idea what's going on here? I think it's a session thing, but I'm a bit out of my depth.

**Comment by kinngh** [comment]
@willmclellarn is it possible to share a screen recording of this either here or over on my [twitter](https://twitter.com/kinngh)? I believe I know the issue I just want to see how to reproduce it^

**Comment by willmclellarn** [comment]
Absolutely - making this now and will send to your twitter, appreciate the help!

**Comment by kinngh** [comment]
Just an update: The current CSP issue doesn't affect any functionality based on testing this repo as-is and production apps^

**Comment by kinngh** [comment]
Fixed.
