### ISSUE TITLE
Cannot find the implementation of Abort method.

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-node-express-mongodb-app#80]
**Hi Harshdeep, I hope you're having a fantastic day. So today I was just trying to figure out how things are engineered in this template. Can you please tell me why did you use error.Abort while throwing an error because I can't find the implementation of this method and it seems that you're applying this method on a string. Your response would be appreciated.**

```
const updateDashboardURLs = async (apiKey, appUrl) => {
  const accessToken = await ensureAuthenticatedPartners();

  const redirectURLs = appUrl.endsWith("/")
    ? [`${appUrl}auth/tokens`, `${appUrl}auth/callback`]
    : [`${appUrl}/auth/tokens`, `${appUrl}/auth/callback`];

  const urls = {
    applicationUrl: appUrl,
    redirectUrlWhitelist: redirectURLs,
  };

  const result = await partnersRequest(UpdateAppURLQuery, accessToken, {
    apiKey,
    ...urls,
  });
  if (result.appUpdate.userErrors.length > 0) {
    const errors = result.appUpdate.userErrors
      .map((error) => error.message)
      .join(", ");

    throw new errors.Abort(errors);
  }
};
```

**Comment by kinngh** [comment]
that should be `throw new AbortError(errors);`, I might have missed during updating the script. I've made a new commit to the project that fixes this - thank you for flagging it!
