### ISSUE TITLE
React issue

### ISSUE THREAD

**Issue by mediumhust** [kinngh/shopify-node-express-mongodb-app#83]
Hi, **Harshdeep**

I have a little issue with React on Devtools when clone your repository and start app.
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```
Thank!

**Comment by mediumhust** [comment]
Hi, **Harshdeep**
Sorry for my delay reply!
I'm working on the base repo.
Thank!

**Comment by kinngh** [comment]
Cannot replicate the error, can you please add screenshots / videos / something so I can see what's happening?

**Comment by mediumhust** [comment]
Thank
