### ISSUE TITLE
App crash trigger by outside request

### ISSUE THREAD

**Issue by embebe2021** [kinngh/shopify-node-express-mongodb-app#86]
Hi Harshdeep, Hope you're having a wonderful day.
I found some way to make app disable in Store Admin page from outside request.
First, i use guest mode in Chrome browser, then i and go to path: https://app-domain/auth/callback?shop=my-shop-name
Now i cant use my app untill uninstall and reinstall the app.

**Comment by kinngh** [comment]
Let me take a look at this in the morning^

**Comment by kinngh** [comment]
Cannot reliably reproduce the error. I cloned the repo, made a fresh app and installed the app on the store. 

1. On a logged in account, it redirected me back to auth, redid the auth and took me to the app.
2. On a logged in account with no permissions, it threw me out and the app was still ok and accessible.
3. In incognito, it asked me to log in and it was still accessible.
4. In incognito, after I logged in with proper access it redid auth and took me to app.
5. In incognito, after I logged in with wrong account it threw me out and the app was still accessible.

The URL in question was `https://subdomain.ngrok-free.app/auth/callback?shop=testStore.myshopify.com`

Can you please add in any more information like logs, a video on how to reproduce the error and/or more so I can investigate this?

**Comment by embebe2021** [comment]
[cinnamon-2023-06-25T020632+0700.webm](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/91905692/839e5490-c5da-4675-a781-ceac6649cdbd)
This is my testing video, i build frontend part and start to install app, everything work welly, so i deciced to check /auth route and find this issue.

**Comment by kinngh** [comment]
Managed to reproduce this locally - what's happening is it can't get out of the iFrame. I tried a workaround with ExitFrame but that seems to be failing too and looks like the only option is to send a blank HTML with some JS to replace window location to get it working. I'll push a fix as soon as possible on this. Thank you for taking the time to flag this!

**Comment by embebe2021** [comment]
I really like the way you authenticate in this boilerplate, however I think the following code is the main cause of the problem, maybe we should redesign it in a better way.
![boilerplate issue](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/91905692/8a87a6ef-c4dd-4257-a411-3d4d34b616d1)

**Comment by kinngh** [comment]
That's what I'm doing right now^

**Comment by kinngh** [comment]
Aight I'm gonna have to do an entire rewrite of the auth. For now, you can just go on with building your app, thank you for flagging this I'm gonna have to take a deep look at how I want to do this without breaking existing installations, and have a drop in solution so existing apps can just copy/paste and be good to go

**Comment by kinngh** [comment]
@embebe2021 Can you test this out now? [bbacb9](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/272fc15b8fcbad950a80e803c64cc8722dbbacb9)

I also noticed another bug that got fixed with exit frame, but now we don't delete the older sessions or mark as inactive since we only mark it active once the entire auth process is complete. If a rogue ping is sent to any of the routes, it redirects you to `/exitframe/shop` instead to exit the iFrame and proceed with auth and then overwrite the sessions to be safe.

**Comment by embebe2021** [comment]
hi @kinngh , how a nice work, i went through your solution, it seems to be a good way, i think i will need a time to take a closer look at this solution in a few days, please leave this thread open for the next few days as I can't view it right now, thank you ^^

**Comment by kinngh** [comment]
Yep!
