### ISSUE TITLE
App Proxy | Cannot escape Ngrok page

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-node-express-mongodb-app#88]
Hi Harshdeep, I am trying to use app proxy in my app and when I go to my the url <https://url.com>/apps/express-proxy/json , I am redirected to NGROK 6024 page and I can't get pass it. It keeps redirecting me to this error even after clicking visit site. I believe I have  set up everything properly and proxy url is available in store's apps section.

**Comment by kinngh** [comment]
Are you passing the bypass headers?

**Comment by Hamzakdev112** [comment]
I tried passing it. It didn't work. maybe I was passing it the wrong way. This is what I did.
 
```
app.use(Express.json());
  app.use(cors());
  app.use((req,res,next)=>{
    res.setHeader("ngrok-skip-browser-warning", "69420")
    next()
  })
```

**Comment by kinngh** [comment]
Please don't try to do this globally, add this to the individual fetch on your client side where you're making that request.

```
await fetch(`/proxy/route`, {
  headers: { 
    'ngrok-skip-browser-warning': 'aaa', 
    'Bypass-Tunnel-Reminder': 'true' 
  }
}
```

**Comment by Hamzakdev112** [comment]
It worked. Thank you big bro.
