### ISSUE TITLE
Shopify Proxy 426 error

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-node-express-mongodb-app#92]
I have deployed my app on Railway, and everything is working fine. However, I am not able to use Shopify proxy. Apparently, Shopify sends an HTTP 1.0 request to the server, which is not supported in Railway. Do you know of any workarounds or any other platforms for deployment that have a free or low-cost tier?

**Comment by kinngh** [comment]
Yep that's a Shopify thing and Railway can't work around it. You can either move to Heroku or Fly.io
