### ISSUE TITLE
How to do auth on shopify mobile app? 

### ISSUE THREAD

**Issue by makasanas** [kinngh/shopify-node-express-mongodb-app#94]
Remote redirect not working on shopify mobile app.

Here is more context on this. Every shopify app now also need optimise that way so it's work perfect on [shopify mobile app](https://shopify.dev/docs/api/app-bridge/optimized-loading). 

So when I load app from mobile app it's work fine until session expire. Once session is expire then as your current implementation it's go to `exitframe` and  then `exitframe` load re-auth process. 

`redirect.dispatch(Redirect.Action.REMOTE, decodeURIComponent(redirectUri));`

But because of `Redirect.Action.REMOTE` not support or may be not working in mobile app. It's never call auth again. so in mobile app user enable to use app until they load app again from any browser and finish re-auth flow.

**Comment by kinngh** [comment]
Can you be more specific? It lacks a lot of context and while you know exactly what you're talking about, I have 0 context on what's happening or what you're referring to.

**Comment by makasanas** [comment]
@kinngh added more context here.

**Comment by kinngh** [comment]
Error reproduced. Working on a fix

**Comment by kinngh** [comment]
This is going to be a tough one to fix, honestly. I'm yet to test this with AppBridge CDN, but as far as the current one is concerned, can you replace your entire ExitFrame file with below? This opens the browser to auth instead of doing it in the app. I'm also starting to take note of how others are doing it, so this could take a while. For now, can you test this in mobile app and on your browser to see if it's redirecting properly?

```javascript
import { Loading, useAppBridge } from "@shopify/app-bridge-react";
import { useEffect } from "react";

const ExitFrame = (props) => {
  const app = useAppBridge();

  useEffect(() => {
    const params = new URLSearchParams(window.location.href);
    let redirectUri = params.get("redirectUri");
    if (props.shop) {
      redirectUri = `https://${appOrigin}/auth?shop=${props.shop}`;
    }
    window.open(decodeURIComponent(redirectUri), "_top");
  }, [app]);

  return <Loading />;
};

export default ExitFrame;
```

**Comment by makasanas** [comment]
If you are using ngrock then I think you can do quick testing by commenting this [`session?.expires`](https://github.com/kinngh/shopify-node-express-mongodb-app/blob/0883207d2b6bb3f075a0c72e849cd97b1abfab1f/server/middleware/verifyRequest.js#L22) if block it will redirect us to always for re-authentication. I think that is quick way to test thing.

**Comment by kinngh** [comment]
@makasanas Mate. There's no _thinking_, can you test it out on mobile and report in?

**Comment by makasanas** [comment]
Here is solution for this. This is way you can easily [debug](https://shopify.dev/docs/api/app-bridge/previous-versions/debugging) in embedded app's WebView. 

```javascript
import { useEffect } from "react";
import { useParams } from "react-router-dom";
import { Loading, useAppBridge, useNavigate } from "@shopify/app-bridge-react";
import { Redirect } from "@shopify/app-bridge/actions";
import { isMobile, isShopifyEmbedded } from "@shopify/app-bridge/utilities";

const ExitFrame = () => {
  const { shop } = useParams();
  const app = useAppBridge();
  const navigateTo = useNavigate();

  useEffect(() => {
    const params = new URLSearchParams(window.location.href);
    let redirectUri = params.get("redirectUri");
    if (shop) {
      redirectUri = `https://${appOrigin}/auth?shop=${shop}`;
    }

    if (isMobile() && isShopifyEmbedded()) {
      navigateTo(decodeURIComponent(redirectUri), { replace: false, target: "host" });
    } else {
      const redirect = Redirect.create(app);
      redirect.dispatch(Redirect.Action.REMOTE, decodeURIComponent(redirectUri));
    }
  }, [app]);

  return <Loading />;
};

export default ExitFrame;

```

**Comment by kinngh** [comment]
...this is based on `react-router-dom`. I have an _actual_ fix being tested by other engineers and once they report in I'll make an update. Thank you for flagging the issue and a _potential_ solution.
