### ISSUE TITLE
Set ENV in the `Dockerfile` for Fly.io 

### ISSUE THREAD

**Issue by jonasmatuliauskas** [kinngh/shopify-node-express-mongodb-app#98]
Hello, Harshdeep Singh Hura 👋 

I want to upload an app to fly.io, but get an error:
```
...
 => CACHED [base 2/2] WORKDIR /app                                                                                                                                                         0.0s
 => CACHED [build 1/6] RUN apt-get update -qq &&     apt-get install -y build-essential pkg-config python-is-python3                                                                       0.0s
 => CACHED [build 2/6] COPY --link package-lock.json package.json ./                                                                                                                       0.0s
 => CACHED [build 3/6] RUN npm ci --include=dev                                                                                                                                            0.0s
 => [build 4/6] COPY --link . .                                                                                                                                                            0.0s
 => ERROR [build 5/6] RUN npm run build                                                                                                                                                    1.1s
------                                                                                                                                                                                          
 > [build 5/6] RUN npm run build:
#0 0.560 
#0 0.560 > shopify-express-boilerplate@0.0.6 build
#0 0.560 > vite build --config=./client/vite.config.cjs
#0 0.560 
#0 1.072 failed to load config from /app/client/vite.config.cjs
#0 1.073 error during build:
#0 1.073 TypeError: Cannot read properties of undefined (reading 'replace')
#0 1.073     at Object.<anonymous> (/app/client/vite.config.cjs:70:35)
#0 1.073     at Module._compile (node:internal/modules/cjs/loader:1254:14)
#0 1.073     at _require.extensions.<computed> [as .js] (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:66253:24)
#0 1.073     at Module.load (node:internal/modules/cjs/loader:1117:32)
#0 1.073     at Module._load (node:internal/modules/cjs/loader:958:12)
#0 1.073     at Module.require (node:internal/modules/cjs/loader:1141:19)
#0 1.073     at require (node:internal/modules/cjs/helpers:110:18)
#0 1.073     at loadConfigFromBundledFile (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:66261:21)
#0 1.073     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#0 1.073     at async loadConfigFromFile (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:66086:28)
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
```

In the code `process.env.<...>` can't access values unless I set it in the `Dockerfile`. Is it safe?

<img width="925" alt="image" src="https://github.com/kinngh/shopify-node-express-mongodb-app/assets/102950681/49dc5879-e9d9-43df-a1f1-07a02329c676">

**Comment by kinngh** [comment]
Hey @jonasmatuliauskas ! 

I don't have enough experience with Docker or Fly.io to comment on that. I can see though that it's having issues at build, so you can use the `ARG` to pass almost everything except for `MONGO_URL` and `SHOPIFY_APP_SECRET`, which isn't required at build time.

Though I did search a little and the recommendation has been to use a `docker-compose.yml` file, and ChatGPT also seems to be recommending the same. I'm gonna keep this issue open while I play around with this over the weekend, unless you find a setup that works.^

**Comment by jonasmatuliauskas** [comment]
Where do you recommend deploy an app? Heroku?

**Comment by kinngh** [comment]
Yep! I've deployed for years on Heroku, behind a Cloudflare cache layer

**Comment by jonasmatuliauskas** [comment]
Perhaps, do you have and can share a `Dockerfile`? I try deploy to Heroku, but get an error: 
```
jonas@.... shopify-app-mongodb % git push heroku main                                              
Enumerating objects: 91, done.
Counting objects: 100% (91/91), done.
Delta compression using up to 10 threads
Compressing objects: 100% (82/82), done.
Writing objects: 100% (91/91), 50.02 KiB | 25.01 MiB/s, done.
Total 91 (delta 8), reused 72 (delta 0), pack-reused 0
remote: Updated 56 paths from 7eeac8c
remote: Compressing source files... done.
remote: Building source:
remote: === Fetching app code
remote: 
remote: =!= There were problems parsing your heroku.yml. We've detected the following issues:
remote: 
remote: build.docker.web references a Dockerfile that does not exist
remote: Verifying deploy...
remote: 
remote: !       Push rejected to shopify-mongo-app.
remote: 
To https://git.heroku.com/shopify-mongo-app.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shopify-mongo-app.git'
```

Use this instruction: https://shopify.dev/docs/apps/deployment/web

`heroku.yml` file:
```
build:
  docker:
    web: Dockerfile
  config:
    SHOPIFY_API_KEY: <...>

```

**Comment by jonasmatuliauskas** [comment]
It's enough to get success deploy. Thank you!
<img width="668" alt="image" src="https://github.com/kinngh/shopify-node-express-mongodb-app/assets/23294704/36ea2d8c-b179-47f7-a0ca-84dac937e2d2">

I have one more question about:
`https://ngrokurl.io/auth?shop=mystorename.myshopify.com`
https://github.com/kinngh/shopify-node-express-mongodb-app/blob/main/docs/SETUP.md

How it will work in the end? I mean, I will build an app based on your boilerplate and submit it for review and approval for Shopify,  to be published and accessible for everyone, and for them (Shopify during review and for everyone), it works normally or will I have to give them information on how to install it? Your approach is not default to start an installation, by default it has to be installed using this button:
<img width="1242" alt="image" src="https://github.com/kinngh/shopify-node-express-mongodb-app/assets/23294704/fef4733e-c605-48c3-9841-28134f74a4ba">

**Comment by kinngh** [comment]
So what's broken is the dev mode. In dev mode, Vite and Express run on different ports and using Ngrok you can expose only one. In prod mode, we're only using one port, which is controlled by env's `PORT` variable, meaning you can do a normal install using select store when running in prod mode by running `npm run start`, so no, you don't have to provide installation instructions to anyone as long as you're running in production mode^

**Comment by Hamzakdev112** [comment]
You need to remove .env from Docker Ignore file
